using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace DotCL.Generators;

[Generator]
public class LispDocGenerator : ISourceGenerator
{
    private const string AttributeSource = @"// <auto-generated/>
using System;
namespace DotCL {
    /// <summary>
    /// Marks a C# method as the implementation of a Lisp built-in function.
    /// The generator extracts the &lt;lispdoc&gt; XML comment element and emits
    /// it as a Lisp function docstring (available via (documentation 'name 'function)).
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    internal sealed class LispDocAttribute : Attribute {
        public string LispName { get; }
        public LispDocAttribute(string lispName) => LispName = lispName;
    }
}
";

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        context.AddSource("LispDocAttribute.g.cs", AttributeSource);

        if (context.SyntaxReceiver is not SyntaxReceiver receiver) return;

        var entries = new List<(string lispName, string doc)>();

        foreach (var method in receiver.Candidates)
        {
            var lispName = GetLispNameFromSyntax(method);
            if (lispName is null) continue;

            // Read doc comment directly from syntax trivia — works without GenerateDocumentationFile.
            var xmlDoc = ReadDocTrivia(method);
            if (xmlDoc is null) continue;

            var doc = ExtractLispDoc(xmlDoc);
            if (string.IsNullOrWhiteSpace(doc)) continue;

            entries.Add((lispName, doc));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace DotCL;");
        sb.AppendLine("internal static partial class GeneratedDocs {");
        sb.AppendLine("    internal static void Register() {");
        foreach (var (name, doc) in entries)
            sb.AppendLine($"        Runtime.SetFunctionDoc(\"{Escape(name)}\", \"{Escape(doc)}\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedDocs.g.cs", sb.ToString());
    }

    // Extract LispName from [LispDoc("NAME")] attribute syntax — no semantic model needed.
    private static string? GetLispNameFromSyntax(MethodDeclarationSyntax method)
    {
        foreach (var attrList in method.AttributeLists)
            foreach (var attr in attrList.Attributes)
            {
                var name = attr.Name.ToString();
                if (name is "LispDoc" or "LispDocAttribute")
                {
                    var arg = attr.ArgumentList?.Arguments.FirstOrDefault();
                    if (arg?.Expression is LiteralExpressionSyntax lit)
                        return lit.Token.ValueText;
                }
            }
        return null;
    }

    // Read the leading /// comment block from syntax trivia and return it as XML string.
    // Works without GenerateDocumentationFile.
    // Note: Roslyn exposes raw /// lines as SingleLineCommentTrivia (same as //),
    // so we distinguish them by checking the text prefix.
    private static string? ReadDocTrivia(MethodDeclarationSyntax method)
    {
        var lines = new List<string>();
        foreach (var trivia in method.GetLeadingTrivia())
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)) continue;
            var raw = trivia.ToFullString().TrimStart();
            if (!raw.StartsWith("///")) continue;        // skip // non-doc comments
            var stripped = Regex.Replace(raw, @"^///\s?", "").TrimEnd();
            lines.Add(stripped);
        }
        if (lines.Count == 0) return null;
        return "<root>" + string.Concat(lines) + "</root>";
    }

    // Extracts text from <lispdoc>. Falls back to <summary> if absent.
    private static string ExtractLispDoc(string xml)
    {
        try
        {
            var doc = XDocument.Parse(xml);
            var lispdoc = doc.Descendants("lispdoc").FirstOrDefault();
            if (lispdoc != null)
                return Normalize(lispdoc.Value);

            var summary = doc.Descendants("summary").FirstOrDefault();
            if (summary != null)
                return Normalize(summary.Value);
        }
        catch { }
        return "";
    }

    private static string Normalize(string s) =>
        Regex.Replace(s.Trim(), @"\s+", " ");

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
}

internal class SyntaxReceiver : ISyntaxReceiver
{
    public List<MethodDeclarationSyntax> Candidates { get; } = new();

    public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
    {
        if (syntaxNode is MethodDeclarationSyntax m &&
            m.AttributeLists.SelectMany(al => al.Attributes)
             .Any(a => { var n = a.Name.ToString(); return n is "LispDoc" or "LispDocAttribute"; }))
            Candidates.Add(m);
    }
}
