;;; dotcl regression test runner
;;; Usage: dotnet run ... -- --asm compiler/cil-out.sil test/regression/run.lisp

(load "test/framework.lisp")

;;; Every .lisp in test/regression/ must be named below: by a LOAD form, or by
;;; a ";; skip:" opt-out line (see test/regression-manifest.lisp). One file sat
;;; here unlisted, and so unrun, for eight days.
(load "test/regression-manifest.lisp")
(check-regression-manifest "test/regression/run.lisp")
;;; Refuse an unknown DOTCL_REGRESSION_TIER before any file loads, not at the
;;; first LOAD-FULL-TIER-ONLY halfway through.
(regression-tier)

;;; Two ways to load a file below:
;;;   (load "test/regression/x.lisp")                     -- every mode
;;;   (load-skip-under-interp "test/regression/x.lisp")   -- not under :INTERPRET
;;; The suite runs in three modes: compiled, *EVALUATOR-MODE* :INTERPRET, and
;;; the emit-free build. The interpret mode starts from the same --asm image as
;;; the compiled run, and a file whose subject does not depend on the evaluator
;;; never reaches the interpreter there, so LOAD-SKIP-UNDER-INTERP (see
;;; test/framework.lisp) skips it in that mode only. Such files are the ones
;;; about a runtime (C#) function, a child process, a compiler optimisation, or
;;; that bind *EVALUATOR-MODE* and run both evaluators themselves.
;;;
;;; The emit-free run still loads every file. It is also the only run that
;;; starts the suite from --core dotcl.core on a DotclNoEmit build, and a file
;;; that does not care about the evaluator can still fail there for that reason.
;;;
;;; The end of every run prints how many marked files were loaded or skipped.
;;;
;;; On the emit-free build every loop in a test file is interpreted. A loop
;;; count that only has to reach past some boundary is kept just past it in
;;; every mode; where a large count means something in compiled code only, the
;;; test asks EMIT-FREE-SCALE (test/framework.lisp) for a smaller one on the
;;; emit-free build, and the end of the run prints how often it did. Counts
;;; that provoke a race or prove constant stack depth are left as they are.
;;;
;;; A third form, (load-full-tier-only "test/regression/x.lisp"), keeps a file
;;; out of the CI run on every push; the full run twice a day loads it (see
;;; LOAD-FULL-TIER-ONLY in test/framework.lisp). With :SKIP-UNDER-INTERP T it is
;;; also skipped under :INTERPRET, like LOAD-SKIP-UNDER-INTERP. Only for files
;;; that are slow and whose subject the full run covers: pack / build, and the
;;; REPL driven as a child process.
;;;
;;; A new file gets a plain LOAD, so it runs in all three modes. Mark it only
;;; after deciding that the interpret mode adds nothing for it. When in doubt,
;;; leave it plain: files that failed in only one of the other modes failed
;;; there because a macro, a declaration or a call reached a different entry
;;; point, even when the subject of the file was a runtime function.

(load "test/regression/closures.lisp")
(load "test/regression/special-vars.lisp")
(load "test/regression/conditions.lisp")
(load "test/regression/type-check-conditions.lisp")
(load "test/regression/restart-cluster-leak.lisp")
(load "test/regression/mini-eval-dotimes.lisp")
(load "test/regression/mvb-bind-snapshot.lisp")
(load-skip-under-interp "test/regression/format-builder-reuse.lisp")
(load-skip-under-interp "test/regression/printer-cons-streaming.lisp")
(load-skip-under-interp "test/regression/printer-depth-threads.lisp")
(load "test/regression/closure-direct-delegate.lisp")
(load-skip-under-interp "test/regression/reader-token-buffer.lisp")
(load "test/regression/handler-case-binding.lisp")
(load "test/regression/handler-case-cluster-identity.lisp")
;;; Assembling a .sil that a released dotcl emitted: only a build with the emitter
;;; assembles one at all.
(when (find :dotcl-emit *features*)
  (load-skip-under-interp "test/regression/legacy-sil-handler-case.lisp"))
(load "test/regression/arith-funcall-fast-path.lisp")
(load "test/regression/num-not-equal-binary.lisp")
(load-skip-under-interp "test/regression/seq-no-materialize.lisp")
(load-skip-under-interp "test/regression/seq-from-end-calls.lisp")
(load-skip-under-interp "test/regression/nuget-layout-key.lisp")
(load-skip-under-interp "test/regression/maphash-search-concat.lisp")
(load "test/regression/sym-pkg-site-cache.lisp")
(load-skip-under-interp "test/regression/qualified-nil-canonical.lisp")
(load-skip-under-interp "test/regression/unit-holder-liveness.lisp")
(load-skip-under-interp "test/regression/write-sequence-paths.lisp")
(load "test/regression/sealed-core-types.lisp")
(load "test/regression/dotimes-counter-slot.lisp")
(load-skip-under-interp "test/regression/mini-eval-builtins.lisp")
(load-skip-under-interp "test/regression/interp-eval-boundary.lisp")
(load "test/regression/eval-progn-sequential.lisp")
(load "test/regression/eval-progn-values.lisp")
(load "test/regression/intrinsic-function-fallback.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/cli-asm-flag-order.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/cli-missing-file.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/cli-subcommand-position.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/cli-argument-errors.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/cli-stdin-script.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/console-code-page-restore.lisp"))
(when (find :dotcl-emit *features*) (load-full-tier-only "test/regression/packed-app-r2r-sibling.lisp" :skip-under-interp t))
(load-skip-under-interp "test/regression/probe-file-directory.lisp")
(load-skip-under-interp "test/regression/logical-pathname-designator.lisp")
(load-skip-under-interp "test/regression/merge-pathnames-version.lisp")
(load-skip-under-interp "test/regression/uiop-native-namestring-windows.lisp")
(load "test/regression/dotcl-native-namestring.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/cli-script-arguments.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/user-init-file-location.lisp"))
(load-skip-under-interp "test/regression/interp-lexical-function.lisp")
(load-skip-under-interp "test/regression/interp-setq-symbol-macro.lisp")
(load-skip-under-interp "test/regression/interp-let-star-special.lisp")
(load-skip-under-interp "test/regression/interp-lambda-list-check.lisp")
(load-skip-under-interp "test/regression/builtin-arity.lisp")
(load-skip-under-interp "test/regression/interp-go-tag-namespace.lisp")
(load-skip-under-interp "test/regression/interp-go-marker.lisp")
(load-skip-under-interp "test/regression/interp-restart-options.lisp")
(load-skip-under-interp "test/regression/interp-special-params.lisp")
(load-skip-under-interp "test/regression/restart-princ-report.lisp")
(load-skip-under-interp "test/regression/interp-closure-arity.lisp")
(load-skip-under-interp "test/regression/interp-tail-calls.lisp")
(load-skip-under-interp "test/regression/interp-special-decl.lisp")
(load-skip-under-interp "test/regression/interp-macrolet-environment.lisp")
(load-skip-under-interp "test/regression/macrolet-whole-environment.lisp")
(load "test/regression/class-of-bit-vector.lisp")
(load "test/regression/fasl-symbol-after-shadowing-import.lisp")
(load-skip-under-interp "test/regression/interp-setf-lowering.lisp")
(load-skip-under-interp "test/regression/interp-function-namespace.lisp")
(load-skip-under-interp "test/regression/interp-restart-condition-association.lisp")
(load-skip-under-interp "test/regression/interp-optional-stream-arg.lisp")
(load-skip-under-interp "test/regression/interp-raw-dotnet-arity-error.lisp")
(load-skip-under-interp "test/regression/minus-function.lisp")
(load-skip-under-interp "test/regression/interp-symbol-macrolet-violation.lisp")
(load-skip-under-interp "test/regression/interp-funcall-designator.lisp")
(load-skip-under-interp "test/regression/interp-block-lexical-scope.lisp")
(load-skip-under-interp "test/regression/interp-deep-throw.lisp")
(load-skip-under-interp "test/regression/interp-defclass-metaclass.lisp")
(load-skip-under-interp "test/regression/interp-symbol-macrolet-shadowing.lisp")
(load "test/regression/interp-symbol-macrolet-call-boundary.lisp")
(load-skip-under-interp "test/regression/interp-handler-case-no-error-scope.lisp")
(load-skip-under-interp "test/regression/interp-anonymous-restart.lisp")
(load-skip-under-interp "test/regression/interp-macrolet-shadowing.lisp")
(load-skip-under-interp "test/regression/interp-defvar-documentation.lisp")
(load-skip-under-interp "test/regression/interp-class-allocation-slot.lisp")
(load-skip-under-interp "test/regression/assoc-alist-entry-check.lisp")
(load-skip-under-interp "test/regression/interp-allow-other-keys-first.lisp")
(load-skip-under-interp "test/regression/interp-symbol-macro-marker.lisp")
(load-skip-under-interp "test/regression/macrolet-shadows-handler.lisp")
(load-skip-under-interp "test/regression/random-state-readable-print.lisp")
(load-skip-under-interp "test/regression/interp-special-param-binding.lisp")
(load-skip-under-interp "test/regression/interp-defun-declarations.lisp")
(load-skip-under-interp "test/regression/interp-defun-docstring.lisp")
(load-skip-under-interp "test/regression/interp-defconstant-marks-constant.lisp")
(load "test/regression/macroexpand-all.lisp")
(load "test/regression/macrolet-expander-lexical-env.lisp")
(load "test/regression/symbol-macro-env-identity.lisp")
(load "test/regression/setf-shadowed-cl-accessor.lisp")
(load "test/regression/compiler-let.lisp")
(load "test/regression/macroexpand-hook.lisp")
(load-skip-under-interp "test/regression/interp-macroexpand-hook-reentry.lisp")
(load-skip-under-interp "test/regression/interp-operator-package-bridge.lisp")
(load "test/regression/declaim-optimize-debug.lisp")
(load "test/regression/interp-backtrace-frames.lisp")
(load-skip-under-interp "test/regression/interp-handler-raw-dotnet.lisp")
(load "test/regression/declaim-optimize-safety.lisp")
(load "test/regression/throw-no-catcher.lisp")
(load "test/regression/interrupt-poll.lisp")
(load "test/regression/clos.lisp")
(load "test/regression/defmethod-on-gf-alias.lisp")
(load "test/regression/symbol-function-nil-t.lisp")
(load "test/regression/sequences.lisp")
(load "test/regression/analysis.lisp")
(load "test/regression/recent-fixes.lisp")
(load-skip-under-interp "test/regression/fasl-eh-nested-in-cleanup.lisp")
(load-skip-under-interp "test/regression/print-object-struct-include.lisp")
(load "test/regression/threading.lisp")
(load "test/regression/atomic-cas.lisp")
(load "test/regression/parallel-eval.lisp")
(load "test/regression/eval-progn-releases-eval-lock.lisp")
(load "test/regression/compile-long-self-calling-function-in-thread.lisp")
(load "test/regression/thread-stack-deep-nesting.lisp")
(load "test/regression/parallel-compile-tables.lisp")
(load "test/regression/loop-prologue-order.lisp")
(load-skip-under-interp "test/regression/directory-subdirectories.lisp")
(load "test/regression/directory-wild-inferiors-zero-levels.lisp")
(load "test/regression/mop.lisp")
(load-skip-under-interp "test/regression/mop-name-pairs.lisp")
(load-skip-under-interp "test/regression/funcallable-cpl.lisp")
(load-skip-under-interp "test/regression/funcallable-default-initargs.lisp")
(load-skip-under-interp "test/regression/type-of-class.lisp")
(load "test/regression/function-lambda-list.lisp")
(load "test/regression/class-direct-subclasses.lisp")
(load "test/regression/slot-definition-attrs.lisp")
(load-skip-under-interp "test/regression/amop-method-construction.lisp")
(load-skip-under-interp "test/regression/amop-method-class-slots.lisp")
(load "test/regression/amop-method-lambda-shape.lisp")
(load-skip-under-interp "test/regression/amop-allocate-instance-metaobject.lisp")
(load-skip-under-interp "test/regression/frame-source-location.lisp")
(load "test/regression/frame-locals.lisp")
(load "test/regression/frame-specials.lisp")
(load-skip-under-interp "test/regression/dynamic-slots.lisp")
(load "test/regression/svuc-methods-on-standard-class.lisp")
;;; DOTNET:DEFINE-CLASS builds a .NET type at run time (AssemblyBuilder /
;;; TypeBuilder), so these files cannot even load on a build without an emitter.
;;; They define their classes at top level, which is why the guard is per file
;;; rather than per test.
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/net-class.lisp"))
(load-skip-under-interp "test/regression/stream-error-io.lisp")
(load-skip-under-interp "test/regression/socket-listen-no-hang.lisp")
(load-skip-under-interp "test/regression/to-stream-close.lisp")
(load-skip-under-interp "test/regression/bivalent-buffered-write.lisp")
(load-skip-under-interp "test/regression/read-delimited-list.lisp")
(load-skip-under-interp "test/regression/read-preserving-whitespace.lisp")
(load "test/regression/reader-macro-unread-char.lisp")
(load-skip-under-interp "test/regression/echo-stream-read.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/define-class-self.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/define-class-spec-errors.lisp"))
;;; Not guarded: registering handlers emits nothing, and the emit-free build
;;; is the one it exists for.
(load "test/regression/register-class-handlers.lisp")
(load-skip-under-interp "test/regression/delegate-marshal.lisp")
(load-skip-under-interp "test/regression/host-thread-registry.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/foreign-callback.lisp"))
(when (find :dotcl-emit *features*)
  (load-skip-under-interp "test/regression/ffi-varargs.lisp")
  ;; Its argument-conversion tests call sprintf variadically.
  (load-skip-under-interp "test/regression/ffi-value-fidelity.lisp"))
;; The memory round trips need no C call, so they run everywhere.
(when (find :dotcl-emit *features*)
  (load-skip-under-interp "test/regression/ffi-memory-fidelity.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/call-out.lisp"))
(load "test/regression/cross-package-fn-aliasing.lisp")
(load "test/regression/destructuring-bind-key-shape.lisp")
(load "test/regression/destructuring-arg-count.lisp")
(load-skip-under-interp "test/regression/asdf-registry-invalidation.lisp")
(load-skip-under-interp "test/regression/nuget-asdf-component.lisp")
(load-skip-under-interp "test/regression/nuget-library-package.lisp")
(load-skip-under-interp "test/regression/pack-system-fasl.lisp")
(load-skip-under-interp "test/regression/pack-system-version.lisp")
(load "test/regression/pack-asd-version-nuget.lisp")
(load-full-tier-only "test/regression/pack-missing-dependency.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/pack-stock-asdf.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/pack-entry-point.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/pack-library.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/pack-help.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/build-modules.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/build-stock-asdf.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/build-deps.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/pack-authors.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/pack-generator-note.lisp" :skip-under-interp t)
(load "test/regression/defstruct-conc-name.lisp")
(load "test/regression/unquote-user-function.lisp")
(load "test/regression/unused-rest-consing.lisp")
(load "test/regression/mv-pair-consing.lisp")
(load "test/regression/illegal-function-call.lisp")
(load "test/regression/remove-direct-delegate.lisp")
(load "test/regression/sort-direct-delegate.lisp")
(load "test/regression/stable-sort-stability.lisp")
(load "test/regression/adjoin-direct-delegate.lisp")
(load-skip-under-interp "test/regression/fasl-template-symbol-intern.lisp")
(load-skip-under-interp "test/regression/fasl-deep-constant.lisp")
(load-skip-under-interp "test/regression/foreign-fasl.lisp")
;; The bundled Quicklisp client is generated by make compile-quicklisp-fasl; a tree
;; without it (CI before its pack step) has nothing to test.
(when (probe-file "contrib/quicklisp/quicklisp.lisp")
  (load-skip-under-interp "test/regression/quicklisp-bundle-loader.lisp")
  (load-skip-under-interp "test/regression/quicklisp-asdf-system.lisp"))
;;; Builds its inputs with compile-file, so it needs an emitter. The bundle
;;; LOADER is present on an emit-free build too, but making a bundle to feed it
;;; would mean carrying one in from another build.
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-bundle.lisp"))
(load "test/regression/optional-direct-delegate.lisp")
(load-skip-under-interp "test/regression/dotnet-invoke-cache.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/dotnet-type-collision.lisp"))
(load "test/regression/dotnet-direct-dispatch.lisp")
(load "test/regression/dotnet-char-overload.lisp")
(load "test/regression/dotnet-typed-inference.lisp")
(load-skip-under-interp "test/regression/static-generic.lisp")
(load-skip-under-interp "test/regression/generic-type-compose.lisp")
(load "test/regression/dotnet-specializer.lisp")
(load-skip-under-interp "test/regression/dotnet-interface-dispatch.lisp")
(load "test/regression/dotnet-typep-class-name.lisp")
(load-skip-under-interp "test/regression/dotnet-open-generic.lisp")
(load "test/regression/dotnet-extension-generic.lisp")
(load-skip-under-interp "test/regression/dotnet-optional-parameters.lisp")
(load-skip-under-interp "test/regression/dotnet-to-stream-oneway.lisp")
(load-skip-under-interp "test/regression/dotnet-explicit-interface.lisp")
(load-skip-under-interp "test/regression/dotnet-extension-cache.lisp")
(load-skip-under-interp "test/regression/dotnet-members.lisp")
(load "test/regression/fasl-lambda-list.lisp")
(load-skip-under-interp "test/regression/dotnet-documentation.lisp")
(load-skip-under-interp "test/regression/dotnet-name-string-representations.lisp")
(load-skip-under-interp "test/regression/lsp-api-completions.lisp")
(load-skip-under-interp "test/regression/lsp-documentation-url.lisp")
(load-skip-under-interp "test/regression/lsp-describe-at.lisp")
(load "test/regression/describe-object.lisp")
(load-skip-under-interp "test/regression/xc-standard-specials.lisp")
(load-full-tier-only "test/regression/repl-completion.lisp" :skip-under-interp t)
(load-skip-under-interp "test/regression/repl-render.lisp")
(load-skip-under-interp "test/regression/repl-commands.lisp")
(load-skip-under-interp "test/regression/repl-multiline.lisp")
(load-skip-under-interp "test/regression/repl-history.lisp")
(load-full-tier-only "test/regression/repl-history-variables.lisp")
(load-full-tier-only "test/regression/repl-input-interrupt.lisp")
(load-full-tier-only "test/regression/stdin-bom-crlf.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/stdin-ctrl-z.lisp" :skip-under-interp t)
(load-skip-under-interp "test/regression/run-program-input-file-bytes.lisp")
(load-skip-under-interp "test/regression/run-program-batch-args.lisp")
(load-skip-under-interp "test/regression/run-program-external-format.lisp")
(load-skip-under-interp "test/regression/launch-process-binary-stream.lisp")
(load-skip-under-interp "test/regression/run-program-background-child.lisp")
(load-full-tier-only "test/regression/repl-piped-debugger.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/repl-runtime-error-debugger.lisp")
(load-full-tier-only "test/regression/repl-color.lisp" :skip-under-interp t)
(load-skip-under-interp "test/regression/repl-shell-mode.lisp")
(load-skip-under-interp "test/regression/repl-command-mode.lisp")
(load-full-tier-only "test/regression/repl-menu.lisp" :skip-under-interp t)
(load-full-tier-only "test/regression/repl-dumb-terminal.lisp" :skip-under-interp t)
(load-skip-under-interp "test/regression/repl-completion-menu.lisp")
(load-skip-under-interp "test/regression/repl-frame-menu.lisp")
(load-skip-under-interp "test/regression/repl-paren-match.lisp")
(load-skip-under-interp "test/regression/repl-syntax-highlight.lisp")
(load "test/regression/debugger-source.lisp")
(load-full-tier-only "test/regression/debugger-hook-returns.lisp")
(load "test/regression/labels-circular-constant.lisp")
(load-skip-under-interp "test/regression/unread-char-position.lisp")
(load-skip-under-interp "test/regression/rank0-initial-contents.lisp")
(load-skip-under-interp "test/regression/pprint-dispatch-nested.lisp")
(load "test/regression/upgraded-array-element-type.lisp")
(load-skip-under-interp "test/regression/dotnet-implicit-and-write.lisp")
(load "test/regression/dotnet-speculative-resolve.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-symbol-syntax.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-load-form-literal.lisp"))
(load "test/regression/dotnet-callback-nlx.lisp")
(load-skip-under-interp "test/regression/dotnet-lisp-receiver.lisp")
(load "test/regression/dotnet-chain.lisp")
(load "test/regression/string-cmp-direct.lisp")
(load-skip-under-interp "test/regression/format-e-rounding.lisp")
(load "test/regression/format-fixed-exact-rounding.lisp")
(load "test/regression/float-infinity-print.lisp")
(load "test/regression/float-floor-mod.lisp")
(load-skip-under-interp "test/regression/print-base-radix.lisp")
(load-skip-under-interp "test/regression/dotnet-await.lisp")
(load "test/regression/async.lisp")
(load "test/regression/async-throw-continuation.lisp")
(load "test/regression/native-int-arith.lisp")
(load "test/regression/native-int-slots.lisp")
(load "test/regression/self-fn-prelude.lisp")
(load "test/regression/sym-fn-call-site.lisp")
(load-skip-under-interp "test/regression/fasl-sym-call-site.lisp")
;;; Compiles files at run time, so it needs an emitter.
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-string-literal.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-literal-data.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-literal-shared-identity.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-literal-cross-identity.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/fasl-literal-reader-vars.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-closure-direct.lisp"))
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/fasl-constant-function.lisp"))
(load "test/regression/inline-expansion.lisp")
(load "test/regression/inline-macrolet-scope.lisp")
(load "test/regression/inline-tail-probe.lisp")
(load "test/regression/local-inline.lisp")
(load "test/regression/nary-fixnum-arith.lisp")
(load-skip-under-interp "test/regression/package-local-nicknames.lisp")
(load-skip-under-interp "test/regression/defpackage-missing-package.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/dotnet-void-values.lisp"))
(load "test/regression/find-symbol-no-consing.lisp")
(load "test/regression/decimal.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/dotnet-numeric-marshal.lisp"))
(load "test/regression/long-rep-locals.lisp")
(load "test/regression/aref-native-index.lisp")
(load "test/regression/aref-bounds.lisp")
(load "test/regression/string-index-bounds.lisp")
(load "test/regression/numeric-array-storage.lisp")
(load "test/regression/optional-param-types.lisp")
(load "test/regression/numeric-array-inference.lisp")
(load "test/regression/array-element-type-upgrading.lisp")
(load "test/regression/struct-slot-function-type.lisp")
(load "test/regression/deftype-name-vs-class.lisp")
(load "test/regression/deftype-expansion-class-change.lisp")
(load "test/regression/funcallable-slot-boundp.lisp")
(load "test/regression/char-eq-identity.lisp")
(load-skip-under-interp "test/regression/cf-accessor-keeps-gf.lisp")
(load-skip-under-interp "test/regression/fasl-accessor-ic.lisp")
(load-skip-under-interp "test/regression/string-char-code-typed.lisp")
(load-skip-under-interp "test/regression/string-backing-hoist-gate.lisp")
(load "test/regression/simple-array-predicates.lisp")
(load "test/regression/simple-array-declaration-check.lisp")
(load "test/regression/struct-slot-typed.lisp")
(load "test/regression/struct-slot-type-safety.lisp")
(load "test/regression/struct-redefinition.lisp")
(load "test/regression/declarations-through-block.lisp")
(load "test/regression/do-step-temp-types.lisp")
(load-skip-under-interp "test/regression/fixnum-param-native-arith.lisp")
(load-skip-under-interp "test/regression/float-literal-native-arith.lisp")
(load-skip-under-interp "test/regression/declared-array-native-aref.lisp")
(load-skip-under-interp "test/regression/array-backing-hoist.lisp")
(load-skip-under-interp "test/regression/defconstant-value-fold.lisp")
(load-skip-under-interp "test/regression/struct-slot-array-aref.lisp")
(load-skip-under-interp "test/regression/struct-slot-element-entries.lisp")
(load "test/regression/struct-slot-single-value.lisp")
(load "test/regression/struct-typep-runtime.lisp")
(load "test/regression/typep-unknown-type.lisp")
(load "test/regression/truename-symlink.lisp")
(load "test/regression/interp-macrolet-setf-place.lisp")
(load "test/regression/pprint-format-block-stream-column.lisp")
(load "test/regression/pprint-format-block-nested-positions.lisp")
(load "test/regression/pprint-print-object-start-column.lisp")
(load "test/regression/pprint-unrelated-stream.lisp")
(load "test/regression/print-circle-print-object.lisp")
(load "test/regression/documentation-setf-method-combination.lisp")
(load "test/regression/find-class-cache.lisp")
(load "test/regression/typep-built-tests.lisp")
(load "test/regression/copy-seq-packed.lisp")
(load "test/regression/bit-funcall.lisp")
(load "test/regression/labels-once.lisp")
(load "test/regression/stack-probe-memo.lisp")
(load "test/regression/element-reader-single-value.lisp")
(load-skip-under-interp "test/regression/ftype-float-return.lisp")
(load "test/regression/inferred-return-type-scope.lisp")
(load-skip-under-interp "test/regression/struct-raw-backing-hoist.lisp")
(load-skip-under-interp "test/regression/fixnum-leaf-range-struct-slot.lisp")
(load-skip-under-interp "test/regression/fixnum-leaf-range-length.lisp")
(load-skip-under-interp "test/regression/fixnum-leaf-range-char-code.lisp")
(load-skip-under-interp "test/regression/fixnum-leaf-range-mod-rem.lisp")
(load-skip-under-interp "test/regression/fixnum-leaf-range-if.lisp")
(load "test/regression/fixnum-param-long-slot.lisp")
(load "test/regression/let-star-special-unwind.lisp")
(load "test/regression/lift-abort-stale-local.lisp")
(load-skip-under-interp "test/regression/macro-char-roundtrip-values.lisp")
(load-skip-under-interp "test/regression/readtable-macro-function-identity.lisp")
(load-skip-under-interp "test/regression/format-nested-sharp-conditional.lisp")
(load "test/regression/setf-expansion-operator-form.lisp")
(load "test/regression/defclass-metaclass-class-options.lisp")
(load "test/regression/the-fixnum-range-license.lisp")
(load-skip-under-interp "test/regression/contrib-renamed-names.lisp")
(load-skip-under-interp "test/regression/fixnum-arith-return-type.lisp")
(load "test/regression/package-error-message.lisp")
(load-skip-under-interp "test/regression/read-suppress-no-intern.lisp")
(load-skip-under-interp "test/regression/documentation-class-object.lisp")
(load "test/regression/documentation-gf-fn-object-deftype.lisp")
(load "test/regression/documentation-setf-name-and-object-clear.lisp")
(load "test/regression/read-time-eval-no-values.lisp")
(load "test/regression/defconstant-compile-time.lisp")
(load-skip-under-interp "test/regression/nontoplevel-defmacro-compile-file.lisp")
(load-skip-under-interp "test/regression/eval-when-ct-definitions-persist.lisp")
(load-skip-under-interp "test/regression/eval-when-compile-time-too.lisp")
(load-skip-under-interp "test/regression/cf-early-defun-restore.lisp")
(load-skip-under-interp "test/regression/native-float-locals.lisp")
(load "test/regression/signed-byte-typep.lisp")
(load "test/regression/handler-case-noerror-capture.lisp")
(load-skip-under-interp "test/regression/process.lisp")
(load-skip-under-interp "test/regression/env-vars.lisp")
(load-skip-under-interp "test/regression/project-core-concat.lisp")
(load-skip-under-interp "test/regression/dotnet-trim-type-refs.lisp")
(load "test/regression/typep-specialized-integer-array.lisp")
(load "test/regression/gray-streams.lisp")
(load-skip-under-interp "test/regression/string-streams.lisp")
(load "test/regression/compile-state-registry.lisp")
(load "test/regression/tco-self-symbol.lisp")
(load "test/regression/tail-prefix-size-gate.lisp")
(load "test/regression/key-shared-body.lisp")
(load "test/regression/keyword-literal-cache.lisp")
(load "test/regression/positional-shared-body.lisp")
(load "test/regression/labels-self-tco.lisp")
(load "test/regression/labels-closure-tco.lisp")
(load "test/regression/labels-self-call-from-closure.lisp")
(load-skip-under-interp "test/regression/schar-typed-value.lisp")
(load-skip-under-interp "test/regression/fixnum-operand-spill.lisp")
(load "test/regression/direct-closure-stack.lisp")
(load "test/regression/handler-case-deep-signal.lisp")
(load "test/regression/restart-case-deep-invoke.lisp")
(load "test/regression/nonlocal-exit-deep-crossing.lisp")
(load "test/regression/closure-in-cleanup.lisp")
(load "test/regression/closure-key-check.lisp")
(load "test/regression/nconc2-inline.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/precompiled-only.lisp"))
(load-skip-under-interp "test/regression/lexical.lisp")
(load "test/regression/keyword-capture-collision.lisp")
(load "test/regression/cross-package-capture.lisp")
(load "test/regression/deep-expansion-closure-capture.lisp")
(load "test/regression/struct-keyword-ctor.lisp")
(load-skip-under-interp "test/regression/defpackage-documentation.lisp")
(load-skip-under-interp "test/regression/cl-builtin-documentation.lisp")
(load-skip-under-interp "test/regression/lispdoc-documentation.lisp")
(load-skip-under-interp "test/regression/variable-documentation.lisp")
(load-skip-under-interp "test/regression/typexpand.lisp")
(load-skip-under-interp "test/regression/hash-numeric-keys.lisp")
(load-skip-under-interp "test/regression/hash-table-test-arg.lisp")
(load "test/regression/type-decl-shadow.lisp")
(load "test/regression/symbol-macro-shadow.lisp")
(load "test/regression/native-slot-shadow.lisp")
(load-skip-under-interp "test/regression/host-call.lisp")
(load "test/regression/closure-boundary-decl.lisp")
(load "test/regression/function-body-reset.lisp")
(load "test/regression/declaration-type-exclusive.lisp")
(load-skip-under-interp "test/regression/global-notinline.lisp")
(load-skip-under-interp "test/regression/host-marshal.lisp")
(load "test/regression/interrupt-thread.lisp")
(load-skip-under-interp "test/regression/declared-type-warning.lisp")
(load "test/regression/boxed-fixnum-as-long.lisp")
(load-skip-under-interp "test/regression/astral-external-format.lisp")
(load "test/regression/external-format-code-pages.lisp")
(load-skip-under-interp "test/regression/xref.lisp")
(load-skip-under-interp "test/regression/cf-nested-load-defs.lisp")
(load-skip-under-interp "test/regression/save-app-preloaded-systems.lisp")
(load "test/regression/defun-paren-name.lisp")
(load-skip-under-interp "test/regression/reader-eof.lisp")
(load-skip-under-interp "test/regression/load-stream-position.lisp")
(load-skip-under-interp "test/regression/nil-t-package-prefix.lisp")
(load-skip-under-interp "test/regression/backquote-expansion.lisp")
(load "test/regression/backquote-vector-dotted-tail.lisp")
(load "test/regression/read-delimited-list-shared-reader.lisp")
(load "test/regression/sym-eq-inline.lisp")
(load-skip-under-interp "test/regression/internal-time-units.lisp")
;;; Every test here compiles a lambda read in a shadowing package, i.e. asserts
;;; how the COMPILER resolves the name. A build with no emitter has no compiler
;;; to ask.
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/shadowed-cl-function-name.lisp"))
(load-skip-under-interp "test/regression/append-long-list.lisp")
(load "test/regression/string-literal-statement-position.lisp")
(load "test/regression/toplevel-locally.lisp")
(load "test/regression/toplevel-macrolet.lisp")
(load-skip-under-interp "test/regression/print-readably-depth.lisp")
(load-skip-under-interp "test/regression/print-readably-princ.lisp")
(load "test/regression/let-body-chunking.lisp")
(load "test/regression/copy-structure-paths.lisp")
(load "test/regression/struct-predicate-name-clash.lisp")
(load "test/regression/optimize-debug-zero.lisp")
(load "test/regression/interp-arg-errors.lisp")
(load "test/regression/gf-arity1-dispatch.lisp")
(load "test/regression/rest-param-scope.lisp")
(load-skip-under-interp "test/regression/integer-arith-no-ratio.lisp")
(load "test/regression/gf-zero-arg-dispatch.lisp")
(load "test/regression/package-var-type-error.lisp")
(load-skip-under-interp "test/regression/dotnet-type-alias.lisp")
(load-skip-under-interp "test/regression/fasl-cache-clean.lisp")
(load-skip-under-interp "test/regression/jit-profile-path.lisp")
(load "test/regression/key-check-const-array.lisp")
(load "test/regression/nary-fixnum-index.lisp")
(load "test/regression/unboxed-aref-any-index.lisp")
(load-skip-under-interp "test/regression/packed-array-alloc.lisp")
(load-skip-under-interp "test/regression/bit-array-type-check.lisp")
(load-skip-under-interp "test/regression/shared-initialize-span.lisp")
(load "test/regression/eql-dispatch-loose.lisp")
(load-skip-under-interp "test/regression/eql-method-redefinition.lisp")
(load "test/regression/mv-pair-return.lisp")
(load "test/regression/list-traversal-type-check.lisp")
(load "test/regression/fixnum-slot-arith.lisp")
(load-skip-under-interp "test/regression/toplevel-loop-consing.lisp")
(load "test/regression/mv-primary-twin.lisp")
(load "test/regression/mv-call-site-mode.lisp")
(load-skip-under-interp "test/regression/reinitialize-instance-consing.lisp")
(load "test/regression/apply-consing.lisp")
(load-skip-under-interp "test/regression/condition-report.lisp")
(load-skip-under-interp "test/regression/car-cdr-type-error.lisp")
(load-skip-under-interp "test/regression/float-exponent-marker.lisp")
(load-skip-under-interp "test/regression/format-g-digits.lisp")
(load-skip-under-interp "test/regression/printer-abbreviations.lisp")
(load-skip-under-interp "test/regression/print-not-readable-object.lisp")
(load "test/regression/constant-assignment.lisp")
(load "test/regression/constant-binding.lisp")
(load-skip-under-interp "test/regression/ffi-uint64.lisp")
(load-skip-under-interp "test/regression/ffi-pointer-range.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/ffi-pointer-call.lisp"))
(load-skip-under-interp "test/regression/format-g-shortest.lisp")
(load-skip-under-interp "test/regression/format-fixed-round-trip.lisp")
(load "test/regression/function-lambda-list-compiled.lisp")
(load "test/regression/complex-double-arith.lisp")
(load-skip-under-interp "test/regression/complex-double-representation.lisp")
(load-skip-under-interp "test/regression/exact-rounding-remainder.lisp")
(load-skip-under-interp "test/regression/rational-known-reduced.lisp")
(load-skip-under-interp "test/regression/integer-comparison-direct.lisp")
(load "test/regression/search-direct-entries.lisp")
(load "test/regression/list-inline-conses.lisp")
(load "test/regression/mapcar-multi-list.lisp")
(load-skip-under-interp "test/regression/remove-no-predicate-closure.lisp")
(load-skip-under-interp "test/regression/sequence-conversion-exact.lisp")
(load-skip-under-interp "test/regression/remove-vector-bitmap.lisp")
(load-skip-under-interp "test/regression/sort-reuses-conses.lisp")
(load "test/regression/map-and-list-keywords.lisp")
(load "test/regression/quoted-literal-identity.lisp")
(load-skip-under-interp "test/regression/set-ops-default-path.lisp")
(load-skip-under-interp "test/regression/seq-direct-entries-2.lisp")
(load-skip-under-interp "test/regression/remove-duplicates-exact.lisp")
(load "test/regression/key-direct-entry.lisp")
(load "test/regression/rest-direct-entry.lisp")
(load-skip-under-interp "test/regression/string-backing-consing.lisp")
(load-skip-under-interp "test/regression/substitute-consing.lisp")
(load-skip-under-interp "test/regression/mismatch-consing.lisp")
(load-skip-under-interp "test/regression/mismatch-bounding-indices.lisp")
(load-skip-under-interp "test/regression/reader-share-table-consing.lisp")
(load-skip-under-interp "test/regression/share-ref-unmatched.lisp")
(load-skip-under-interp "test/regression/file-position-characters.lisp")
(load-skip-under-interp "test/regression/io-stream-file-position.lisp")
(load-skip-under-interp "test/regression/load-file-position-bytes.lisp")
(load-skip-under-interp "test/regression/open-file-error.lisp")
(load "test/regression/macrolet-environment-symbol-macrolet.lisp")
(load "test/regression/macrolet-expander-call-site-env.lisp")
(load "test/regression/destructuring-key-position.lisp")
(load "test/regression/format-iteration-count.lisp")
(load "test/regression/print-symbol-trailing-sign.lisp")
(load "test/regression/pprint-trim-fill-pointer-string.lisp")
(load-skip-under-interp "test/regression/append-atomic.lisp")
(load-skip-under-interp "test/regression/format-directive-consing.lisp")
(load-skip-under-interp "test/regression/format-up-and-out.lisp")
(load-skip-under-interp "test/regression/format-missing-argument.lisp")
(load-skip-under-interp "test/regression/make-array-no-dims-array.lisp")
(load "test/regression/multiple-values-direct.lisp")
(load "test/regression/multiple-value-propagation.lisp")
(load "test/regression/gf-multi-method-dispatch.lisp")
(load "test/regression/gf-keyword-validation.lisp")
(load "test/regression/complex-float-contagion.lisp")
(load "test/regression/native-float-slot-store.lisp")
(load "test/regression/nary-float-arith.lisp")
(load "test/regression/native-float-abs.lisp")
(load "test/regression/sqrt-declared-double.lisp")
(load "test/regression/letstar-declaration-scope.lisp")
(load "test/regression/native-character-locals.lisp")
(load "test/regression/float-nan-comparison.lisp")
(load "test/regression/mixed-float-comparison.lisp")
(load "test/regression/statement-position-conditional.lisp")
(load "test/regression/flet-capture-lifting.lisp")
(load "test/regression/local-function-inline.lisp")
(load-skip-under-interp "test/regression/float-format-introspection.lisp")
(load-skip-under-interp "test/regression/bit-vector-word-ops.lisp")
(load "test/regression/gf-aux-method-dispatch.lisp")
(load-skip-under-interp "test/regression/shared-initialize-alloc.lisp")

(load-skip-under-interp "test/regression/frame-flag-default.lisp")
(load "test/regression/native-raw-entry.lisp")
(load "test/regression/main-thread.lisp")
(load-skip-under-interp "test/regression/format-control-directive-args.lisp")
(load-skip-under-interp "test/regression/fresh-line-after-print.lisp")
(load-skip-under-interp "test/regression/funcallable-print-object.lisp")
(load "test/regression/symbol-macro-let-shadow-setf.lisp")
(load-skip-under-interp "test/regression/core-labels-not-in-cl-user.lisp")
(load "test/regression/metaclass-default-initargs.lisp")
(load "test/regression/metaclass-direct-superclasses.lisp")
(load "test/regression/metaclass-direct-slots.lisp")
(load "test/regression/metaclass-reinitialize.lisp")
(load "test/regression/slotd-metaobject-type.lisp")
(load-skip-under-interp "test/regression/no-applicable-method-protocol.lisp")
(load-skip-under-interp "test/regression/sort-non-strict-predicate.lisp")
(load-skip-under-interp "test/regression/mop-class-name-symbols.lisp")
(load "test/regression/metaclass-finalized-p.lisp")
;;; COMPILE needs an emitter.
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/compile-warnings-p.lisp"))
(load "test/regression/lambda-macroexpand.lisp")
(load-skip-under-interp "test/regression/gf-class-option-name.lisp")
(load-skip-under-interp "test/regression/print-unreadable-type-name.lisp")
(load "test/regression/interp-setq-global-symbol-macro.lisp")
(load-skip-under-interp "test/regression/cf-defclass-compile-time.lisp")
(load "test/regression/metaclass-slot-accessors.lisp")
(load "test/regression/finalize-inheritance-new-class.lisp")
(load "test/regression/ldb-constant-bytespec.lisp")
(load "test/regression/dpb-constant-bytespec.lisp")
(load-skip-under-interp "test/regression/setf-gf-name.lisp")
(load-skip-under-interp "test/regression/ensure-gf-class.lisp")
(load "test/regression/flet-hides-macro-in-environment.lisp")
(load "test/regression/mvb-portable-expansion.lisp")
(load-skip-under-interp "test/regression/pprint-nested-per-line-prefix.lisp")
(load-skip-under-interp "test/regression/scale-float-range.lisp")
(load "test/regression/ash-fast-path-range.lisp")
(load "test/regression/modular-ash.lisp")
(load "test/regression/fixnum-wrap-consumers.lisp")
(load "test/regression/modular-arith-declared-types.lisp")
(load "test/regression/print-readably-standard-object.lisp")
(load "test/regression/setf-find-class-name.lisp")
(load "test/regression/pprint-user-code-staged-order.lisp")
(load "test/regression/make-instance-condition-report.lisp")
(load "test/regression/pprint-fill-after-literal-newline.lisp")
(load "test/regression/format-user-output-in-block-columns.lisp")
(load "test/regression/format-slash-missing-argument.lisp")
(load "test/regression/directory-sorted.lisp")
(load "test/regression/defmethod-multiple-qualifiers.lisp")
(load "test/regression/method-combination-error-message.lisp")
(load "test/regression/method-combination-user-operator.lisp")
(load "test/regression/single-valued-args-of-inlined-calls.lisp")
(load "test/regression/format-string-inside-logical-block.lisp")
(load "test/regression/the-fixnum-logand-bignum-operand.lisp")
(load "test/regression/expt-fixnum-fast-path.lisp")
(load "test/regression/map-into-list-arguments.lisp")
(load "test/regression/hash-table-iteration-order.lisp")
(load "test/regression/long-form-method-combination-forms.lisp")
(load "test/regression/compiler-macro-funcall-form.lisp")
(load "test/regression/make-array-displaced-bounds.lisp")
(load "test/regression/loop-with-destructuring.lisp")
(load "test/regression/method-lambda-list-unspecialized.lisp")
(load "test/regression/y-or-n-p.lisp")
(load "test/regression/setf-cons-accessor-once.lisp")
(load "test/regression/adjust-array-displaced-to-string.lisp")
(load "test/regression/asdf-provide-keeps-system.lisp")
(load "test/regression/displaced-string-sharing.lisp")
(load "test/regression/notinline-nested-lambda.lisp")
(load "test/regression/complex-array-element-type.lisp")
(load "test/regression/signed-byte-file-stream.lisp")
(load "test/regression/flet-cl-symbol-name-variable.lisp")
(load "test/regression/parse-integer-junk-allowed-index.lisp")
(load "test/regression/method-qualifier-t.lisp")
(load "test/regression/binary-file-stream-bom.lisp")
(load "test/regression/handler-bind-clr-exception.lisp")
(load "test/regression/return-from-scan-nested-macros.lisp")
(load "test/regression/slot-name-packages.lisp")
(load "test/regression/class-redefinition-instances.lisp")
(load "test/regression/pinned-vector.lisp")
(load "test/regression/sequence-type-rank.lisp")
(load-skip-under-interp "test/regression/cf-export-courtesy.lisp")
(load "test/regression/typep-shadowed-builtin-name.lisp")
(load "test/regression/standard-readtable-no-fasl-syntax.lisp")
(load "test/regression/row-major-aref-setf-string.lisp")
(load "test/regression/package-local-nicknames-designators.lisp")
(load "test/regression/make-instance-structure-class.lisp")
(load "test/regression/function-names-from-fasl.lisp")
(load "test/regression/nsublis-destructive.lisp")
(load "test/regression/supplied-p-closure-assigned.lisp")
(load "test/regression/cltl2-variable-information.lisp")
(load "test/regression/format-control-char-vector.lisp")
(load "test/regression/complex-array-default-element.lisp")
(load "test/regression/expt-rational-ratio.lisp")
(load "test/regression/local-function-other-package.lisp")
(load "test/regression/make-instance-slot-definition.lisp")
(load "test/regression/slot-definition-initialize-instance.lisp")
(load "test/regression/mop-setf-function-names.lisp")
(load "test/regression/defsetf-lambda-list.lisp")
(load "test/regression/forward-referenced-metaclass.lisp")
(load-skip-under-interp "test/regression/xc-macrolet-local-function.lisp")
(load "test/regression/ucd-char-name-table.lisp")
(load "test/regression/cf-literal-symbols-uncached.lisp")
(load "test/regression/cf-toplevel-run-once.lisp")
(load "test/regression/cf-toplevel-merged.lisp")
(load "test/regression/labels-self-call-hidden-in-literal.lisp")
(load "test/regression/block-test-position-hidden-return.lisp")
(load "test/regression/map-merge-result-element-type.lisp")
(load "test/regression/flet-lifted-function-as-value-via-macro.lisp")
(load "test/regression/eval-self-evaluating-atoms.lisp")
(load "test/regression/cf-deferred-early-defun.lisp")
(load "test/regression/cf-macroexpansion-error.lisp")
(load "test/regression/macrolet-expander-interpreted.lisp")
(load "test/regression/defpackage-data-expansion.lisp")
(load "test/regression/cf-deferred-macro-expander.lisp")
(load "test/regression/cf-deferred-lexical-environment.lisp")
(load "test/regression/defmethod-data-expansion.lisp")
(load "test/regression/emitted-helper-no-inlining.lisp")
(load "test/regression/cf-hash-table-literal-prototype.lisp")
(load "test/regression/cf-saving-slots-literal-direct.lisp")
(load "test/regression/cf-mlf-batch.lisp")
(load "test/regression/cf-fasl-data-literals.lisp")
(load "test/regression/macro-function-function-names.lisp")
(load "test/regression/cf-mlf-call-form.lisp")
(load "test/regression/cf-struct-make-load-form.lisp")
(load "test/regression/u64-modular-lane.lisp")
(load "test/regression/mod-rem-ratio.lisp")
(load "test/regression/hof-literal-lambda-and-floor-split.lisp")
(load "test/regression/equal-hash-char-backed-string.lisp")
(load "test/regression/eval-when-source-load-discard.lisp")
(load "test/regression/gf-dispatch-many-classes.lisp")
(load "test/regression/accessor-polymorphic-call-site.lisp")
(load "test/regression/gf-dispatch-superclass-change.lisp")
(load "test/regression/accessor-after-slot-reorder.lisp")
(load "test/regression/gf-anonymous-redefinition.lisp")
(load-skip-under-interp "test/regression/fasl-r2r-in-place.lisp")
(load "test/regression/cf-uninterned-non-ascii.lisp")
(load "test/regression/member-eql-identity.lisp")
(load "test/regression/cltl2-variable-information-file-special.lisp")
(load "test/regression/compile-lambda-no-thunk.lisp")
(load "test/regression/eval-run-once-calls.lisp")
(load "test/regression/cf-definition-journal.lisp")
(load "test/regression/cf-other-thread-definitions.lisp")
(load "test/regression/boole-bignum-operands.lisp")
(load "test/regression/go-from-nested-closure.lisp")
(load "test/regression/let-star-boxed-loop-init.lisp")
(load "test/regression/optional-default-sees-outer-over-later-param.lisp")
(load "test/regression/string-output-stream-base-char.lisp")
(load "test/regression/base-string-class.lisp")
(load "test/regression/make-pathname-directory-string.lisp")
(load "test/regression/condition-print-type-name.lisp")
(load "test/regression/metaclass-around-direct-superclasses.lisp")
(load "test/regression/delete-file-directory-file-form.lisp")
(load "test/regression/slot-documentation-inherited.lisp")
(load "test/regression/slot-type-conjunction.lisp")
(load "test/regression/universal-time-nil-time-zone.lisp")
(load "test/regression/slot-using-class-structure.lisp")
(load "test/regression/logand-chain-compile-time.lisp")
(load "test/regression/local-fn-optional-default-single-value.lisp")
(load "test/regression/flet-block-shadows-outer-block.lisp")
(load "test/regression/setf-local-fn-implicit-block.lisp")
(load "test/regression/setf-local-fn-closure-capture.lisp")
(load "test/regression/special-operator-shadowed-name.lisp")
(load "test/regression/char-name-u-hex-short.lisp")
(load "test/regression/char-name-sbcl-aliases.lisp")
(load "test/regression/hash-table-anonymous-test.lisp")
(load "test/regression/rest-visible-in-key-default.lisp")
(load "test/regression/hash-table-hash-function.lisp")
(when (find :dotcl-emit *features*) (load-skip-under-interp "test/regression/ffi-process-symbols.lisp"))
(load "test/regression/user-class-named-like-system-class.lisp")
(load "test/regression/variable-named-nil-other-package.lisp")
(load "test/regression/equalp-hash-structure-keys.lisp")
(load "test/regression/inner-local-fn-shadows-outer-capture.lisp")
(load "test/regression/setf-nil-function-name.lisp")
(load "test/regression/uaet-character-subtypes.lisp")
(load "test/regression/ratio-huge-parts-to-float.lisp")
(load "test/regression/character-of-vector-string.lisp")
(load "test/regression/intrinsic-arg-protected-region.lisp")
(load "test/regression/restart-case-param-shadows-boxed.lisp")
(load "test/regression/equal-hash-pathname-keys.lisp")
(load "test/regression/sxhash-numbers-by-value.lisp")
(load "test/regression/cf-struct-saving-slots-subset.lisp")
(load "test/regression/print-struct-type-name-package.lisp")
(load "test/regression/read-from-string-file-position.lisp")
(load "test/regression/cf-load-time-value-at-load.lisp")
(load "test/regression/print-circle-call-next-method.lisp")
(load "test/regression/make-hash-table-computed-keyword.lisp")
(load "test/regression/pathname-equal-newest-version.lisp")
(load "test/regression/gf-name-after-delete-package.lisp")
(load "test/regression/logcount-native.lisp")
(load "test/regression/circular-literal-in-tagbody.lisp")
(load "test/regression/circular-literal-in-loop.lisp")
(load "test/regression/logtest-fixnum.lisp")
(load "test/regression/mod-rem-fixnum-by-bignum.lisp")
(load "test/regression/cf-toplevel-macrolet-body.lisp")
(load "test/regression/restart-case-association-scope.lisp")
(load "test/regression/delete-directory.lisp")

(do-tests-summary)
(skip-under-interp-summary)
(regression-tier-summary)
(emit-free-scale-summary)
(cleanup-regression-temp-dir)
(if (= *fail-count* 0)
    (dotcl:quit 0)
    (dotcl:quit 1))
