;;; dotcl regression test runner
;;; Usage: dotnet run ... -- --asm compiler/cil-out.sil test/regression/run.lisp

(load "test/framework.lisp")

(load "test/regression/closures.lisp")
(load "test/regression/special-vars.lisp")
(load "test/regression/conditions.lisp")
(load "test/regression/type-check-conditions.lisp")
(load "test/regression/restart-cluster-leak.lisp")
(load "test/regression/mini-eval-dotimes.lisp")
(load "test/regression/mini-eval-builtins.lisp")
(load "test/regression/interp-eval-boundary.lisp")
(load "test/regression/interp-lexical-function.lisp")
(load "test/regression/interp-setq-symbol-macro.lisp")
(load "test/regression/interp-let-star-special.lisp")
(load "test/regression/interp-lambda-list-check.lisp")
(load "test/regression/builtin-arity.lisp")
(load "test/regression/interp-go-tag-namespace.lisp")
(load "test/regression/interp-go-marker.lisp")
(load "test/regression/interp-restart-options.lisp")
(load "test/regression/interp-closure-arity.lisp")
(load "test/regression/interp-tail-calls.lisp")
(load "test/regression/interp-special-decl.lisp")
(load "test/regression/interp-macrolet-environment.lisp")
(load "test/regression/interp-setf-lowering.lisp")
(load "test/regression/interp-function-namespace.lisp")
(load "test/regression/interp-restart-condition-association.lisp")
(load "test/regression/interp-optional-stream-arg.lisp")
(load "test/regression/interp-raw-dotnet-arity-error.lisp")
(load "test/regression/minus-function.lisp")
(load "test/regression/interp-symbol-macrolet-violation.lisp")
(load "test/regression/interp-funcall-designator.lisp")
(load "test/regression/interp-block-lexical-scope.lisp")
(load "test/regression/interp-deep-throw.lisp")
(load "test/regression/interp-defclass-metaclass.lisp")
(load "test/regression/interp-symbol-macrolet-shadowing.lisp")
(load "test/regression/interp-handler-case-no-error-scope.lisp")
(load "test/regression/interp-anonymous-restart.lisp")
(load "test/regression/interp-macrolet-shadowing.lisp")
(load "test/regression/interp-defvar-documentation.lisp")
(load "test/regression/interp-class-allocation-slot.lisp")
(load "test/regression/assoc-alist-entry-check.lisp")
(load "test/regression/interp-allow-other-keys-first.lisp")
(load "test/regression/interp-symbol-macro-marker.lisp")
(load "test/regression/macrolet-shadows-handler.lisp")
(load "test/regression/random-state-readable-print.lisp")
(load "test/regression/interp-special-param-binding.lisp")
(load "test/regression/interp-defun-declarations.lisp")
(load "test/regression/interp-defun-docstring.lisp")
(load "test/regression/interp-defconstant-marks-constant.lisp")
(load "test/regression/macroexpand-all.lisp")
(load "test/regression/macroexpand-hook.lisp")
(load "test/regression/interp-macroexpand-hook-reentry.lisp")
(load "test/regression/interp-operator-package-bridge.lisp")
(load "test/regression/interp-backtrace-frames.lisp")
(load "test/regression/interp-handler-raw-dotnet.lisp")
(load "test/regression/interrupt-poll.lisp")
(load "test/regression/clos.lisp")
(load "test/regression/sequences.lisp")
(load "test/regression/analysis.lisp")
(load "test/regression/recent-fixes.lisp")
(load "test/regression/fasl-eh-nested-in-cleanup.lisp")
(load "test/regression/print-object-struct-include.lisp")
(load "test/regression/threading.lisp")
(load "test/regression/atomic-cas.lisp")
(load "test/regression/parallel-eval.lisp")
(load "test/regression/parallel-compile-tables.lisp")
(load "test/regression/loop-prologue-order.lisp")
(load "test/regression/directory-subdirectories.lisp")
(load "test/regression/mop.lisp")
(load "test/regression/class-direct-subclasses.lisp")
(load "test/regression/slot-definition-attrs.lisp")
(load "test/regression/amop-method-construction.lisp")
(load "test/regression/frame-source-location.lisp")
(load "test/regression/frame-locals.lisp")
(load "test/regression/frame-specials.lisp")
(load "test/regression/dynamic-slots.lisp")
;;; DOTNET:DEFINE-CLASS builds a .NET type at run time (AssemblyBuilder /
;;; TypeBuilder), so these files cannot even load on a build without an emitter.
;;; They define their classes at top level, which is why the guard is per file
;;; rather than per test.
(when (find :dotcl-emit *features*) (load "test/regression/net-class.lisp"))
(load "test/regression/stream-error-io.lisp")
(load "test/regression/read-delimited-list.lisp")
(load "test/regression/read-preserving-whitespace.lisp")
(load "test/regression/echo-stream-read.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/define-class-self.lisp"))
(load "test/regression/delegate-marshal.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/foreign-callback.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/call-out.lisp"))
(load "test/regression/cross-package-fn-aliasing.lisp")
(load "test/regression/asdf-registry-invalidation.lisp")
(load "test/regression/defstruct-conc-name.lisp")
(load "test/regression/unquote-user-function.lisp")
(load "test/regression/illegal-function-call.lisp")
(load "test/regression/remove-direct-delegate.lisp")
(load "test/regression/sort-direct-delegate.lisp")
(load "test/regression/stable-sort-stability.lisp")
(load "test/regression/adjoin-direct-delegate.lisp")
(load "test/regression/fasl-template-symbol-intern.lisp")
(load "test/regression/fasl-deep-constant.lisp")
(load "test/regression/foreign-fasl.lisp")
(load "test/regression/optional-direct-delegate.lisp")
(load "test/regression/dotnet-invoke-cache.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/dotnet-type-collision.lisp"))
(load "test/regression/dotnet-direct-dispatch.lisp")
(load "test/regression/dotnet-typed-inference.lisp")
(load "test/regression/static-generic.lisp")
(load "test/regression/generic-type-compose.lisp")
(load "test/regression/dotnet-specializer.lisp")
(load "test/regression/dotnet-interface-dispatch.lisp")
(load "test/regression/dotnet-typep-class-name.lisp")
(load "test/regression/dotnet-open-generic.lisp")
(load "test/regression/dotnet-extension-generic.lisp")
(load "test/regression/dotnet-callback-nlx.lisp")
(load "test/regression/dotnet-lisp-receiver.lisp")
(load "test/regression/dotnet-chain.lisp")
(load "test/regression/string-cmp-direct.lisp")
(load "test/regression/format-e-rounding.lisp")
(load "test/regression/float-infinity-print.lisp")
(load "test/regression/print-base-radix.lisp")
(load "test/regression/dotnet-await.lisp")
(load "test/regression/async.lisp")
(load "test/regression/native-int-arith.lisp")
(load "test/regression/native-int-slots.lisp")
(load "test/regression/self-fn-prelude.lisp")
(load "test/regression/sym-fn-call-site.lisp")
(load "test/regression/fasl-sym-call-site.lisp")
;;; Compiles files at run time, so it needs an emitter.
(when (find :dotcl-emit *features*) (load "test/regression/fasl-string-literal.lisp"))
(load "test/regression/inline-expansion.lisp")
(load "test/regression/inline-tail-probe.lisp")
(load "test/regression/decimal.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/dotnet-numeric-marshal.lisp"))
(load "test/regression/long-rep-locals.lisp")
(load "test/regression/aref-native-index.lisp")
(load "test/regression/aref-bounds.lisp")
(load "test/regression/string-index-bounds.lisp")
(load "test/regression/numeric-array-storage.lisp")
(load "test/regression/optional-param-types.lisp")
(load "test/regression/numeric-array-inference.lisp")
(load "test/regression/native-float-locals.lisp")
(load "test/regression/signed-byte-typep.lisp")
(load "test/regression/handler-case-noerror-capture.lisp")
(load "test/regression/process.lisp")
(load "test/regression/env-vars.lisp")
(load "test/regression/project-core-concat.lisp")
(load "test/regression/gray-streams.lisp")
(load "test/regression/string-streams.lisp")
(load "test/regression/compile-state-registry.lisp")
(load "test/regression/tco-self-symbol.lisp")
(load "test/regression/labels-self-tco.lisp")
(load "test/regression/fixnum-operand-spill.lisp")
(load "test/regression/direct-closure-stack.lisp")
(load "test/regression/handler-case-deep-signal.lisp")
(load "test/regression/restart-case-deep-invoke.lisp")
(load "test/regression/nonlocal-exit-deep-crossing.lisp")
(load "test/regression/closure-in-cleanup.lisp")
(load "test/regression/closure-key-check.lisp")
(load "test/regression/nconc2-inline.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/precompiled-only.lisp"))
(load "test/regression/lexical.lisp")
(load "test/regression/keyword-capture-collision.lisp")
(load "test/regression/cross-package-capture.lisp")
(load "test/regression/defpackage-documentation.lisp")
(load "test/regression/hash-numeric-keys.lisp")
(load "test/regression/hash-table-test-arg.lisp")
(load "test/regression/type-decl-shadow.lisp")
(load "test/regression/symbol-macro-shadow.lisp")
(load "test/regression/native-slot-shadow.lisp")
(load "test/regression/host-call.lisp")
(load "test/regression/closure-boundary-decl.lisp")
(load "test/regression/function-body-reset.lisp")
(load "test/regression/declaration-type-exclusive.lisp")
(load "test/regression/global-notinline.lisp")
(load "test/regression/host-marshal.lisp")
(load "test/regression/interrupt-thread.lisp")
(load "test/regression/declared-type-warning.lisp")
(load "test/regression/boxed-fixnum-as-long.lisp")
(load "test/regression/astral-external-format.lisp")
(load "test/regression/xref.lisp")
(load "test/regression/cf-nested-load-defs.lisp")
(load "test/regression/save-app-preloaded-systems.lisp")
(load "test/regression/defun-paren-name.lisp")
(load "test/regression/reader-eof.lisp")
(load "test/regression/load-stream-position.lisp")
(load "test/regression/nil-t-package-prefix.lisp")
(load "test/regression/backquote-expansion.lisp")
(load "test/regression/sym-eq-inline.lisp")
(load "test/regression/internal-time-units.lisp")
(load "test/regression/shadowed-cl-function-name.lisp")
(load "test/regression/append-long-list.lisp")
(load "test/regression/string-literal-statement-position.lisp")
(load "test/regression/toplevel-locally.lisp")
(load "test/regression/let-body-chunking.lisp")

(do-tests-summary)
(if (= *fail-count* 0)
    (dotcl:quit 0)
    (dotcl:quit 1))
