;;; dotcl regression test runner
;;; Usage: dotnet run ... -- --asm compiler/cil-out.sil test/regression/run.lisp

(load "test/framework.lisp")

(load "test/regression/closures.lisp")
(load "test/regression/special-vars.lisp")
(load "test/regression/conditions.lisp")
(load "test/regression/type-check-conditions.lisp")
(load "test/regression/restart-cluster-leak.lisp")
(load "test/regression/mini-eval-dotimes.lisp")
(load "test/regression/mvb-bind-snapshot.lisp")
(load "test/regression/format-builder-reuse.lisp")
(load "test/regression/printer-cons-streaming.lisp")
(load "test/regression/closure-direct-delegate.lisp")
(load "test/regression/reader-token-buffer.lisp")
(load "test/regression/handler-case-binding.lisp")
(load "test/regression/arith-funcall-fast-path.lisp")
(load "test/regression/seq-no-materialize.lisp")
(load "test/regression/seq-from-end-calls.lisp")
(load "test/regression/nuget-layout-key.lisp")
(load "test/regression/maphash-search-concat.lisp")
(load "test/regression/sym-pkg-site-cache.lisp")
(load "test/regression/qualified-nil-canonical.lisp")
(load "test/regression/unit-holder-liveness.lisp")
(load "test/regression/write-sequence-paths.lisp")
(load "test/regression/sealed-core-types.lisp")
(load "test/regression/dotimes-counter-slot.lisp")
(load "test/regression/mini-eval-builtins.lisp")
(load "test/regression/interp-eval-boundary.lisp")
(load "test/regression/eval-progn-sequential.lisp")
(load "test/regression/intrinsic-function-fallback.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/cli-asm-flag-order.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/cli-missing-file.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/cli-subcommand-position.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/cli-argument-errors.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/cli-script-arguments.lisp"))
(load "test/regression/interp-lexical-function.lisp")
(load "test/regression/interp-setq-symbol-macro.lisp")
(load "test/regression/interp-let-star-special.lisp")
(load "test/regression/interp-lambda-list-check.lisp")
(load "test/regression/builtin-arity.lisp")
(load "test/regression/interp-go-tag-namespace.lisp")
(load "test/regression/interp-go-marker.lisp")
(load "test/regression/interp-restart-options.lisp")
(load "test/regression/interp-closure-arity.lisp")
(load "test/regression/interp-tail-calls.lisp")
(load "test/regression/interp-special-decl.lisp")
(load "test/regression/interp-macrolet-environment.lisp")
(load "test/regression/interp-setf-lowering.lisp")
(load "test/regression/interp-function-namespace.lisp")
(load "test/regression/interp-restart-condition-association.lisp")
(load "test/regression/interp-optional-stream-arg.lisp")
(load "test/regression/interp-raw-dotnet-arity-error.lisp")
(load "test/regression/minus-function.lisp")
(load "test/regression/interp-symbol-macrolet-violation.lisp")
(load "test/regression/interp-funcall-designator.lisp")
(load "test/regression/interp-block-lexical-scope.lisp")
(load "test/regression/interp-deep-throw.lisp")
(load "test/regression/interp-defclass-metaclass.lisp")
(load "test/regression/interp-symbol-macrolet-shadowing.lisp")
(load "test/regression/interp-handler-case-no-error-scope.lisp")
(load "test/regression/interp-anonymous-restart.lisp")
(load "test/regression/interp-macrolet-shadowing.lisp")
(load "test/regression/interp-defvar-documentation.lisp")
(load "test/regression/interp-class-allocation-slot.lisp")
(load "test/regression/assoc-alist-entry-check.lisp")
(load "test/regression/interp-allow-other-keys-first.lisp")
(load "test/regression/interp-symbol-macro-marker.lisp")
(load "test/regression/macrolet-shadows-handler.lisp")
(load "test/regression/random-state-readable-print.lisp")
(load "test/regression/interp-special-param-binding.lisp")
(load "test/regression/interp-defun-declarations.lisp")
(load "test/regression/interp-defun-docstring.lisp")
(load "test/regression/interp-defconstant-marks-constant.lisp")
(load "test/regression/macroexpand-all.lisp")
(load "test/regression/macroexpand-hook.lisp")
(load "test/regression/interp-macroexpand-hook-reentry.lisp")
(load "test/regression/interp-operator-package-bridge.lisp")
(load "test/regression/interp-backtrace-frames.lisp")
(load "test/regression/interp-handler-raw-dotnet.lisp")
(load "test/regression/interrupt-poll.lisp")
(load "test/regression/clos.lisp")
(load "test/regression/sequences.lisp")
(load "test/regression/analysis.lisp")
(load "test/regression/recent-fixes.lisp")
(load "test/regression/fasl-eh-nested-in-cleanup.lisp")
(load "test/regression/print-object-struct-include.lisp")
(load "test/regression/threading.lisp")
(load "test/regression/atomic-cas.lisp")
(load "test/regression/parallel-eval.lisp")
(load "test/regression/parallel-compile-tables.lisp")
(load "test/regression/loop-prologue-order.lisp")
(load "test/regression/directory-subdirectories.lisp")
(load "test/regression/mop.lisp")
(load "test/regression/mop-name-pairs.lisp")
(load "test/regression/type-of-class.lisp")
(load "test/regression/function-lambda-list.lisp")
(load "test/regression/class-direct-subclasses.lisp")
(load "test/regression/slot-definition-attrs.lisp")
(load "test/regression/amop-method-construction.lisp")
(load "test/regression/amop-method-class-slots.lisp")
(load "test/regression/frame-source-location.lisp")
(load "test/regression/frame-locals.lisp")
(load "test/regression/frame-specials.lisp")
(load "test/regression/dynamic-slots.lisp")
;;; DOTNET:DEFINE-CLASS builds a .NET type at run time (AssemblyBuilder /
;;; TypeBuilder), so these files cannot even load on a build without an emitter.
;;; They define their classes at top level, which is why the guard is per file
;;; rather than per test.
(when (find :dotcl-emit *features*) (load "test/regression/net-class.lisp"))
(load "test/regression/stream-error-io.lisp")
(load "test/regression/read-delimited-list.lisp")
(load "test/regression/read-preserving-whitespace.lisp")
(load "test/regression/echo-stream-read.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/define-class-self.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/define-class-spec-errors.lisp"))
(load "test/regression/delegate-marshal.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/foreign-callback.lisp"))
;; Skipped on Apple ARM64: :VARARGS handles the argument promotions but not the
;; register/stack split Apple's ARM64 variadic ABI requires, so 6 of the 8 tests
;; there assert an ABI the implementation does not yet honour.
(when (and (find :dotcl-emit *features*)
           (not (find :darwin *features*)))
  (load "test/regression/ffi-varargs.lisp")
  ;; Same guard: its argument-conversion tests call sprintf variadically.
  (load "test/regression/ffi-value-fidelity.lisp"))
;; The memory round trips need no C call, so they run everywhere.
(when (find :dotcl-emit *features*)
  (load "test/regression/ffi-memory-fidelity.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/call-out.lisp"))
(load "test/regression/cross-package-fn-aliasing.lisp")
(load "test/regression/asdf-registry-invalidation.lisp")
(load "test/regression/defstruct-conc-name.lisp")
(load "test/regression/unquote-user-function.lisp")
(load "test/regression/illegal-function-call.lisp")
(load "test/regression/remove-direct-delegate.lisp")
(load "test/regression/sort-direct-delegate.lisp")
(load "test/regression/stable-sort-stability.lisp")
(load "test/regression/adjoin-direct-delegate.lisp")
(load "test/regression/fasl-template-symbol-intern.lisp")
(load "test/regression/fasl-deep-constant.lisp")
(load "test/regression/foreign-fasl.lisp")
;;; Builds its inputs with compile-file, so it needs an emitter. The bundle
;;; LOADER is present on an emit-free build too, but making a bundle to feed it
;;; would mean carrying one in from another build.
(when (find :dotcl-emit *features*) (load "test/regression/fasl-bundle.lisp"))
(load "test/regression/optional-direct-delegate.lisp")
(load "test/regression/dotnet-invoke-cache.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/dotnet-type-collision.lisp"))
(load "test/regression/dotnet-direct-dispatch.lisp")
(load "test/regression/dotnet-typed-inference.lisp")
(load "test/regression/static-generic.lisp")
(load "test/regression/generic-type-compose.lisp")
(load "test/regression/dotnet-specializer.lisp")
(load "test/regression/dotnet-interface-dispatch.lisp")
(load "test/regression/dotnet-typep-class-name.lisp")
(load "test/regression/dotnet-open-generic.lisp")
(load "test/regression/dotnet-extension-generic.lisp")
(load "test/regression/dotnet-optional-parameters.lisp")
(load "test/regression/dotnet-to-stream-oneway.lisp")
(load "test/regression/dotnet-explicit-interface.lisp")
(load "test/regression/dotnet-extension-cache.lisp")
(load "test/regression/dotnet-implicit-and-write.lisp")
(load "test/regression/dotnet-speculative-resolve.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/fasl-symbol-syntax.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/fasl-load-form-literal.lisp"))
(load "test/regression/dotnet-callback-nlx.lisp")
(load "test/regression/dotnet-lisp-receiver.lisp")
(load "test/regression/dotnet-chain.lisp")
(load "test/regression/string-cmp-direct.lisp")
(load "test/regression/format-e-rounding.lisp")
(load "test/regression/float-infinity-print.lisp")
(load "test/regression/print-base-radix.lisp")
(load "test/regression/dotnet-await.lisp")
(load "test/regression/async.lisp")
(load "test/regression/native-int-arith.lisp")
(load "test/regression/native-int-slots.lisp")
(load "test/regression/self-fn-prelude.lisp")
(load "test/regression/sym-fn-call-site.lisp")
(load "test/regression/fasl-sym-call-site.lisp")
;;; Compiles files at run time, so it needs an emitter.
(when (find :dotcl-emit *features*) (load "test/regression/fasl-string-literal.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/fasl-literal-data.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/fasl-closure-direct.lisp"))
(when (find :dotcl-emit *features*) (load "test/regression/fasl-constant-function.lisp"))
(load "test/regression/inline-expansion.lisp")
(load "test/regression/inline-tail-probe.lisp")
(load "test/regression/decimal.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/dotnet-numeric-marshal.lisp"))
(load "test/regression/long-rep-locals.lisp")
(load "test/regression/aref-native-index.lisp")
(load "test/regression/aref-bounds.lisp")
(load "test/regression/string-index-bounds.lisp")
(load "test/regression/numeric-array-storage.lisp")
(load "test/regression/optional-param-types.lisp")
(load "test/regression/numeric-array-inference.lisp")
(load "test/regression/native-float-locals.lisp")
(load "test/regression/signed-byte-typep.lisp")
(load "test/regression/handler-case-noerror-capture.lisp")
(load "test/regression/process.lisp")
(load "test/regression/env-vars.lisp")
(load "test/regression/project-core-concat.lisp")
(load "test/regression/gray-streams.lisp")
(load "test/regression/string-streams.lisp")
(load "test/regression/compile-state-registry.lisp")
(load "test/regression/tco-self-symbol.lisp")
(load "test/regression/labels-self-tco.lisp")
(load "test/regression/fixnum-operand-spill.lisp")
(load "test/regression/direct-closure-stack.lisp")
(load "test/regression/handler-case-deep-signal.lisp")
(load "test/regression/restart-case-deep-invoke.lisp")
(load "test/regression/nonlocal-exit-deep-crossing.lisp")
(load "test/regression/closure-in-cleanup.lisp")
(load "test/regression/closure-key-check.lisp")
(load "test/regression/nconc2-inline.lisp")
(when (find :dotcl-emit *features*) (load "test/regression/precompiled-only.lisp"))
(load "test/regression/lexical.lisp")
(load "test/regression/keyword-capture-collision.lisp")
(load "test/regression/cross-package-capture.lisp")
(load "test/regression/struct-keyword-ctor.lisp")
(load "test/regression/defpackage-documentation.lisp")
(load "test/regression/hash-numeric-keys.lisp")
(load "test/regression/hash-table-test-arg.lisp")
(load "test/regression/type-decl-shadow.lisp")
(load "test/regression/symbol-macro-shadow.lisp")
(load "test/regression/native-slot-shadow.lisp")
(load "test/regression/host-call.lisp")
(load "test/regression/closure-boundary-decl.lisp")
(load "test/regression/function-body-reset.lisp")
(load "test/regression/declaration-type-exclusive.lisp")
(load "test/regression/global-notinline.lisp")
(load "test/regression/host-marshal.lisp")
(load "test/regression/interrupt-thread.lisp")
(load "test/regression/declared-type-warning.lisp")
(load "test/regression/boxed-fixnum-as-long.lisp")
(load "test/regression/astral-external-format.lisp")
(load "test/regression/xref.lisp")
(load "test/regression/cf-nested-load-defs.lisp")
(load "test/regression/save-app-preloaded-systems.lisp")
(load "test/regression/defun-paren-name.lisp")
(load "test/regression/reader-eof.lisp")
(load "test/regression/load-stream-position.lisp")
(load "test/regression/nil-t-package-prefix.lisp")
(load "test/regression/backquote-expansion.lisp")
(load "test/regression/sym-eq-inline.lisp")
(load "test/regression/internal-time-units.lisp")
;;; Every test here compiles a lambda read in a shadowing package, i.e. asserts
;;; how the COMPILER resolves the name. A build with no emitter has no compiler
;;; to ask.
(when (find :dotcl-emit *features*) (load "test/regression/shadowed-cl-function-name.lisp"))
(load "test/regression/append-long-list.lisp")
(load "test/regression/string-literal-statement-position.lisp")
(load "test/regression/toplevel-locally.lisp")
(load "test/regression/toplevel-macrolet.lisp")
(load "test/regression/print-readably-depth.lisp")
(load "test/regression/print-readably-princ.lisp")
(load "test/regression/let-body-chunking.lisp")
(load "test/regression/copy-structure-paths.lisp")
(load "test/regression/struct-predicate-name-clash.lisp")
(load "test/regression/optimize-debug-zero.lisp")
(load "test/regression/interp-arg-errors.lisp")
(load "test/regression/gf-arity1-dispatch.lisp")
(load "test/regression/rest-param-scope.lisp")
(load "test/regression/integer-arith-no-ratio.lisp")
(load "test/regression/gf-zero-arg-dispatch.lisp")
(load "test/regression/package-var-type-error.lisp")
(load "test/regression/dotnet-type-alias.lisp")
(load "test/regression/fasl-cache-clean.lisp")
(load "test/regression/key-check-const-array.lisp")
(load "test/regression/nary-fixnum-index.lisp")
(load "test/regression/unboxed-aref-any-index.lisp")
(load "test/regression/packed-array-alloc.lisp")
(load "test/regression/bit-array-type-check.lisp")
(load "test/regression/shared-initialize-span.lisp")
(load "test/regression/eql-dispatch-loose.lisp")
(load "test/regression/eql-method-redefinition.lisp")
(load "test/regression/mv-pair-return.lisp")
(load "test/regression/list-traversal-type-check.lisp")
(load "test/regression/fixnum-slot-arith.lisp")
(load "test/regression/condition-report.lisp")
(load "test/regression/car-cdr-type-error.lisp")
(load "test/regression/float-exponent-marker.lisp")
(load "test/regression/format-g-digits.lisp")
(load "test/regression/printer-abbreviations.lisp")
(load "test/regression/print-not-readable-object.lisp")
(load "test/regression/constant-assignment.lisp")
(load "test/regression/constant-binding.lisp")
(load "test/regression/ffi-uint64.lisp")
(load "test/regression/format-g-shortest.lisp")
(load "test/regression/format-fixed-round-trip.lisp")
(load "test/regression/function-lambda-list-compiled.lisp")
(load "test/regression/complex-double-arith.lisp")
(load "test/regression/complex-double-representation.lisp")
(load "test/regression/exact-rounding-remainder.lisp")
(load "test/regression/rational-known-reduced.lisp")
(load "test/regression/integer-comparison-direct.lisp")
(load "test/regression/search-direct-entries.lisp")
(load "test/regression/list-inline-conses.lisp")
(load "test/regression/mapcar-multi-list.lisp")
(load "test/regression/remove-no-predicate-closure.lisp")
(load "test/regression/sequence-conversion-exact.lisp")
(load "test/regression/remove-vector-bitmap.lisp")
(load "test/regression/sort-reuses-conses.lisp")
(load "test/regression/map-and-list-keywords.lisp")
(load "test/regression/quoted-literal-identity.lisp")
(load "test/regression/set-ops-default-path.lisp")
(load "test/regression/seq-direct-entries-2.lisp")
(load "test/regression/remove-duplicates-exact.lisp")
(load "test/regression/key-direct-entry.lisp")
(load "test/regression/make-array-no-dims-array.lisp")
(load "test/regression/multiple-values-direct.lisp")
(load "test/regression/multiple-value-propagation.lisp")
(load "test/regression/gf-multi-method-dispatch.lisp")
(load "test/regression/complex-float-contagion.lisp")
(load "test/regression/native-float-slot-store.lisp")
(load "test/regression/nary-float-arith.lisp")
(load "test/regression/native-float-abs.lisp")
(load "test/regression/float-nan-comparison.lisp")
(load "test/regression/mixed-float-comparison.lisp")
(load "test/regression/statement-position-conditional.lisp")
(load "test/regression/flet-capture-lifting.lisp")
(load "test/regression/float-format-introspection.lisp")
(load "test/regression/bit-vector-word-ops.lisp")
(load "test/regression/gf-aux-method-dispatch.lisp")
(load "test/regression/shared-initialize-alloc.lisp")

(load "test/regression/frame-flag-default.lisp")
(load "test/regression/native-raw-entry.lisp")
(load "test/regression/main-thread.lisp")

(do-tests-summary)
(if (= *fail-count* 0)
    (dotcl:quit 0)
    (dotcl:quit 1))
