// gen-utils: code generation utilities for dotcl build
// Usage:
//   gen-utils download   <url> <output-file>
//   gen-utils char-names <ucd-file> <output-cs-file>

using System.Net.Http;
using System.Text;

return args.Length == 0 ? Usage() : args[0] switch
{
    "download"   => await CmdDownload(args[1..]),
    "char-names" => CmdCharNames(args[1..]),
    _            => Usage()
};

static async Task<int> CmdDownload(string[] args)
{
    if (args.Length != 2) return Fail("download <url> <output-file>");
    var (url, path) = (args[0], args[1]);
    Console.WriteLine($"Downloading {url}");
    using var client = new HttpClient();
    var text = await client.GetStringAsync(url);
    File.WriteAllText(path, text, Encoding.UTF8);
    Console.WriteLine($"Wrote {new FileInfo(path).Length / 1024}KB -> {path}");
    return 0;
}

static int CmdCharNames(string[] args)
{
    if (args.Length != 2) return Fail("char-names <ucd-file> <output-cs-file>");
    var (ucdPath, outPath) = (args[0], args[1]);

    Console.WriteLine($"Parsing {ucdPath}");
    var entries = new List<(int Cp, string Name)>();
    foreach (var line in File.ReadLines(ucdPath))
    {
        var s1 = line.IndexOf(';');
        if (s1 < 0) continue;
        var s2 = line.IndexOf(';', s1 + 1);
        if (s2 < 0) continue;
        if (!int.TryParse(line[..s1], System.Globalization.NumberStyles.HexNumber, null, out int cp))
            continue;
        if (cp >= 0x10000 || (cp >= 0xD800 && cp <= 0xDFFF)) continue; // BMP, no surrogates
        var name = line[(s1 + 1)..s2];
        if (name.Length == 0 || name[0] == '<') continue; // skip range markers / control
        entries.Add((cp, name));
    }
    Console.WriteLine($"{entries.Count} named BMP entries");

    Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outPath))!);
    using var w = new StreamWriter(outPath, false, Encoding.UTF8);
    w.WriteLine("// Auto-generated by scripts/GenUtils (gen-utils char-names).");
    w.WriteLine("// Run 'make gen-char-names' to regenerate.");
    w.WriteLine();
    w.WriteLine("namespace DotCL;");
    w.WriteLine("public static partial class Runtime");
    w.WriteLine("{");
    w.WriteLine("    private static class Ucd");
    w.WriteLine("    {");
    w.WriteLine("        internal static readonly System.Collections.Generic.Dictionary<string, char> NameToChar;");
    w.WriteLine("        internal static readonly System.Collections.Generic.Dictionary<char, string> CharToName;");
    w.WriteLine();
    // The table is one string constant, one "XXXX NAME" line per entry, parsed
    // by the type initializer. An array initializer of ~30k (string, char)
    // tuples compiled to ~440 KB of IL in the type initializer, and JIT-compiling
    // that took ~0.45 s the first time a character name missed the small table.
    w.WriteLine("        static Ucd()");
    w.WriteLine("        {");
    w.WriteLine("            var text = Data;");
    w.WriteLine("            int count = 0;");
    w.WriteLine("            foreach (char ch in text) if (ch == '\\n') count++;");
    w.WriteLine("            NameToChar = new System.Collections.Generic.Dictionary<string, char>(");
    w.WriteLine("                count, System.StringComparer.OrdinalIgnoreCase);");
    w.WriteLine("            CharToName = new System.Collections.Generic.Dictionary<char, string>(count);");
    w.WriteLine("            int pos = 0;");
    w.WriteLine("            while (pos < text.Length)");
    w.WriteLine("            {");
    w.WriteLine("                int eol = text.IndexOf('\\n', pos);");
    w.WriteLine("                if (eol < 0) eol = text.Length;");
    w.WriteLine("                int end = eol;");
    w.WriteLine("                if (end > pos && text[end - 1] == '\\r') end--;");
    w.WriteLine("                if (end - pos > 5)");
    w.WriteLine("                {");
    w.WriteLine("                    int code = 0;");
    w.WriteLine("                    for (int i = pos; i < pos + 4; i++)");
    w.WriteLine("                        code = code * 16 + (text[i] <= '9' ? text[i] - '0' : text[i] - 'A' + 10);");
    w.WriteLine("                    char c = (char)code;");
    w.WriteLine("                    string n = text.Substring(pos + 5, end - pos - 5);");
    w.WriteLine("                    NameToChar.TryAdd(n, c);");
    w.WriteLine("                    CharToName.TryAdd(c, n);");
    w.WriteLine("                }");
    w.WriteLine("                pos = eol + 1;");
    w.WriteLine("            }");
    w.WriteLine("        }");
    w.WriteLine();
    w.WriteLine("        private const string Data = @\"");
    foreach (var (cp, name) in entries)
        w.WriteLine($"{cp:X4} {name}");
    w.WriteLine("\";");
    w.WriteLine("    }");
    w.WriteLine("}");
    Console.WriteLine($"Wrote {outPath}");
    return 0;
}

static int Usage()
{
    Console.Error.WriteLine("Usage:");
    Console.Error.WriteLine("  gen-utils download   <url> <output-file>");
    Console.Error.WriteLine("  gen-utils char-names <ucd-file> <output-cs-file>");
    return 1;
}

static int Fail(string msg) { Console.Error.WriteLine($"Usage: gen-utils {msg}"); return 1; }
