// gen-utils — code generation utilities for dotcl build
// Usage:
//   gen-utils download   <url> <output-file>
//   gen-utils char-names <ucd-file> <output-cs-file>

using System.Net.Http;
using System.Text;

return args.Length == 0 ? Usage() : args[0] switch
{
    "download"   => await CmdDownload(args[1..]),
    "char-names" => CmdCharNames(args[1..]),
    _            => Usage()
};

static async Task<int> CmdDownload(string[] args)
{
    if (args.Length != 2) return Fail("download <url> <output-file>");
    var (url, path) = (args[0], args[1]);
    Console.WriteLine($"Downloading {url}");
    using var client = new HttpClient();
    var text = await client.GetStringAsync(url);
    File.WriteAllText(path, text, Encoding.UTF8);
    Console.WriteLine($"Wrote {new FileInfo(path).Length / 1024}KB → {path}");
    return 0;
}

static int CmdCharNames(string[] args)
{
    if (args.Length != 2) return Fail("char-names <ucd-file> <output-cs-file>");
    var (ucdPath, outPath) = (args[0], args[1]);

    Console.WriteLine($"Parsing {ucdPath}");
    var entries = new List<(int Cp, string Name)>();
    foreach (var line in File.ReadLines(ucdPath))
    {
        var s1 = line.IndexOf(';');
        if (s1 < 0) continue;
        var s2 = line.IndexOf(';', s1 + 1);
        if (s2 < 0) continue;
        if (!int.TryParse(line[..s1], System.Globalization.NumberStyles.HexNumber, null, out int cp))
            continue;
        if (cp >= 0x10000 || (cp >= 0xD800 && cp <= 0xDFFF)) continue; // BMP, no surrogates
        var name = line[(s1 + 1)..s2];
        if (name.Length == 0 || name[0] == '<') continue; // skip range markers / control
        entries.Add((cp, name));
    }
    Console.WriteLine($"{entries.Count} named BMP entries");

    Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outPath))!);
    using var w = new StreamWriter(outPath, false, Encoding.UTF8);
    w.WriteLine("// Auto-generated by scripts/GenUtils (gen-utils char-names).");
    w.WriteLine("// Run 'make gen-char-names' to regenerate.");
    w.WriteLine();
    w.WriteLine("namespace DotCL;");
    w.WriteLine("public static partial class Runtime");
    w.WriteLine("{");
    w.WriteLine("    private static class Ucd");
    w.WriteLine("    {");
    w.WriteLine("        internal static readonly System.Collections.Generic.Dictionary<string, char> NameToChar;");
    w.WriteLine("        internal static readonly System.Collections.Generic.Dictionary<char, string> CharToName;");
    w.WriteLine();
    w.WriteLine("        static Ucd()");
    w.WriteLine("        {");
    w.WriteLine("            var data = Data;");
    w.WriteLine("            NameToChar = new System.Collections.Generic.Dictionary<string, char>(");
    w.WriteLine("                data.Length, System.StringComparer.OrdinalIgnoreCase);");
    w.WriteLine("            CharToName = new System.Collections.Generic.Dictionary<char, string>(data.Length);");
    w.WriteLine("            foreach (var (n, c) in data) { NameToChar.TryAdd(n, c); CharToName.TryAdd(c, n); }");
    w.WriteLine("        }");
    w.WriteLine();
    w.WriteLine("        private static readonly (string, char)[] Data =");
    w.WriteLine("        [");
    foreach (var (cp, name) in entries)
        w.WriteLine($"            (\"{name}\", '\\x{cp:X4}'),");
    w.WriteLine("        ];");
    w.WriteLine("    }");
    w.WriteLine("}");
    Console.WriteLine($"Wrote {outPath}");
    return 0;
}

static int Usage()
{
    Console.Error.WriteLine("Usage:");
    Console.Error.WriteLine("  gen-utils download   <url> <output-file>");
    Console.Error.WriteLine("  gen-utils char-names <ucd-file> <output-cs-file>");
    return 1;
}

static int Fail(string msg) { Console.Error.WriteLine($"Usage: gen-utils {msg}"); return 1; }
