#!/bin/bash
# Gate the benchmark time ratios in bench-state.json against bench/ratio-baseline.json.
#
# Usage: check-ratios.sh <bench-state.json> <ratio-baseline.json> <platform>
#
# Checks two things:
#
#   parity/*            every C# parity kernel, individually. A kernel whose
#                       dotcl/C# ratio has grown past baseline * threshold
#                       fails the build.
#   cl-bench median     the median of the cl-bench dotcl/SBCL ratios, as one
#                       number, when a baseline for it exists.
#
# Ratios are keyed by platform. A ratio is a comparison of two programs on one
# machine, which cancels raw clock speed but not much else -- instruction set,
# memory system and .NET version all move it -- so a baseline recorded on one
# platform says nothing about another. A platform with no recorded baseline is
# reported as unbaselined, with its measured ratios printed in the format
# ratio-baseline.json wants, and does NOT fail the build. That is the only
# not-a-failure path here, and it announces itself: a gate that quietly passes
# because it had nothing to compare against is worse than no gate.
#
# bench-state.json is regenerated by every benchmark run and is not tracked, so
# the recorded side has to be its own committed file; it cannot be "last run's
# bench-state.json".

set -u

state_file="${1:-}"
baseline_file="${2:-}"
platform="${3:-}"

if [ -z "$state_file" ] || [ -z "$baseline_file" ] || [ -z "$platform" ]; then
    echo "Usage: $0 <bench-state.json> <ratio-baseline.json> <platform>" >&2
    exit 2
fi

for f in "$state_file" "$baseline_file"; do
    if [ ! -f "$f" ]; then
        echo "check-ratios: $f not found" >&2
        exit 2
    fi
done

# --- baseline ----------------------------------------------------------

threshold=$(sed -n 's/^ *"threshold": *\([0-9.]*\).*/\1/p' "$baseline_file" | head -1)
if [ -z "$threshold" ]; then
    echo "check-ratios: no \"threshold\" in $baseline_file" >&2
    exit 2
fi

# "<platform>/<key>": <number>   ->   <key><TAB><number>
baseline_ratios=$(sed -n "s|^ *\"$platform/\([^\"]*\)\": *\([0-9.]*\),\{0,1\}\$|\1\t\2|p" "$baseline_file")

# --- measured ----------------------------------------------------------

# "name": {... "ratio": <value> ...}   ->   name<TAB>value
# Entries whose ratio is null (a half that errored) are dropped here and
# reported as missing below rather than compared against nothing.
measured=$(sed -n 's/^ *"\([^"]*\)": {.*"ratio": *\([^,}]*\).*/\1\t\2/p' "$state_file" \
    | awk -F'\t' '$2 + 0 == $2 { print $1 "\t" $2 }')

parity_measured=$(echo "$measured" | awk -F'\t' '$1 ~ /^parity\// { print }')

if [ -z "$parity_measured" ]; then
    echo "check-ratios: no parity/* entries in $state_file -- the parity benchmark did not run." >&2
    exit 1
fi

# cl-bench rows are everything that is neither a parity row nor an allocation
# row (those are byte counts; their "ratio" is not a time ratio).
clbench_ratios=$(echo "$measured" \
    | awk -F'\t' '$1 !~ /^parity\// && $1 !~ /\/consed$/ { print $2 }' \
    | sort -g)

lookup_baseline() {
    echo "$baseline_ratios" | awk -F'\t' -v n="$1" '$1 == n { print $2; exit }'
}

# --- parity ------------------------------------------------------------

echo "=== parity ratios (platform: $platform, threshold: ${threshold}x baseline) ==="

failed=0
unbaselined=0
unbaselined_lines=""

while IFS=$'\t' read -r name ratio; do
    [ -z "$name" ] && continue
    base=$(lookup_baseline "$name")
    if [ -z "$base" ]; then
        unbaselined=$((unbaselined + 1))
        unbaselined_lines="$unbaselined_lines    \"$platform/$name\": $ratio,\n"
        printf '  %-28s %8s   (no baseline)\n' "$name" "$ratio"
        continue
    fi
    limit=$(awk "BEGIN { printf \"%.2f\", $base * $threshold }")
    if awk "BEGIN { exit !($ratio > $limit) }"; then
        printf '  %-28s %8s   FAIL  baseline %s, limit %s\n' "$name" "$ratio" "$base" "$limit"
        failed=$((failed + 1))
    else
        printf '  %-28s %8s   ok    baseline %s, limit %s\n' "$name" "$ratio" "$base" "$limit"
    fi
done <<< "$parity_measured"

# --- cl-bench median ---------------------------------------------------

echo "=== cl-bench ratio median ==="

clbench_count=$(echo "$clbench_ratios" | grep -c '[0-9]' || true)
clbench_base=$(lookup_baseline "cl-bench/median")

if [ "$clbench_count" -lt 20 ]; then
    # The cl-bench step runs under `|| true` on purpose: a missing or slow SBCL
    # is a data-collection problem, not a broken build. Keep that policy here,
    # but say out loud that the check did not happen.
    echo "  SKIPPED: only $clbench_count cl-bench ratios in $state_file (need 20)."
elif [ -z "$clbench_base" ]; then
    median=$(echo "$clbench_ratios" | awk '{ v[NR] = $1 }
        END { if (NR % 2) printf "%.2f", v[(NR+1)/2]
              else printf "%.2f", (v[NR/2] + v[NR/2+1]) / 2 }')
    echo "  SKIPPED: no \"$platform/cl-bench/median\" baseline. Measured: $median over $clbench_count benchmarks."
    unbaselined=$((unbaselined + 1))
    unbaselined_lines="$unbaselined_lines    \"$platform/cl-bench/median\": $median,\n"
else
    median=$(echo "$clbench_ratios" | awk '{ v[NR] = $1 }
        END { if (NR % 2) printf "%.2f", v[(NR+1)/2]
              else printf "%.2f", (v[NR/2] + v[NR/2+1]) / 2 }')
    limit=$(awk "BEGIN { printf \"%.2f\", $clbench_base * $threshold }")
    if awk "BEGIN { exit !($median > $limit) }"; then
        printf '  %-28s %8s   FAIL  baseline %s, limit %s (%s benchmarks)\n' \
            "cl-bench/median" "$median" "$clbench_base" "$limit" "$clbench_count"
        failed=$((failed + 1))
    else
        printf '  %-28s %8s   ok    baseline %s, limit %s (%s benchmarks)\n' \
            "cl-bench/median" "$median" "$clbench_base" "$limit" "$clbench_count"
    fi
fi

# --- verdict -----------------------------------------------------------

if [ "$unbaselined" -gt 0 ]; then
    echo ""
    echo "=== $unbaselined measurement(s) have no baseline for platform '$platform' ==="
    echo "Not a failure. To start gating them, add these to the \"ratios\" object"
    echo "in bench/ratio-baseline.json and describe the machine under \"recorded\":"
    echo ""
    printf "$unbaselined_lines"
fi

if [ "$failed" -gt 0 ]; then
    echo ""
    echo "check-ratios: $failed measurement(s) above ${threshold}x their recorded baseline."
    echo "Either the change made them slower, or the baseline is stale --"
    echo "see docs/profiling.md before editing bench/ratio-baseline.json."
    exit 1
fi

echo ""
echo "check-ratios: ok"
exit 0
