#!/bin/bash
# Gate the benchmark time ratios in bench-state.json against bench/ratio-baseline.json.
#
# Usage: check-ratios.sh <bench-state.json> <ratio-baseline.json> <platform>
#
# Checks two things:
#
#   parity/*            every C# parity kernel, individually. A kernel whose
#                       dotcl/C# ratio has grown past baseline * threshold
#                       fails the build.
#   cl-bench median     the median of the cl-bench dotcl/SBCL ratios, as one
#                       number, when a baseline for it exists.
#
# Ratios are keyed by platform. A ratio is a comparison of two programs on one
# machine, which cancels raw clock speed but not much else -- instruction set,
# memory system and .NET version all move it -- so a baseline recorded on one
# platform says nothing about another. A measurement with no recorded baseline
# is reported as unbaselined, with its measured ratio printed in the format
# ratio-baseline.json wants.
#
# Exit status and the last line of output:
#
#   0  "check-ratios: ok -- J judged[, U not judged]"
#        At least one measurement was compared against a baseline and none was
#        over its limit. The not-judged count is on the same line, so a run
#        that judged 1 of 9 cannot be read as the same thing as one that
#        judged 9 of 9.
#   1  "check-ratios: FAIL -- ..."
#        At least one judged measurement was over its limit, or the parity
#        benchmark did not run at all.
#   2  usage error or a missing input file.
#   3  "check-ratios: UNJUDGED -- 0 of N measurement(s) judged ..."
#        Nothing had a baseline, so nothing was checked. This is not "ok": a
#        gate that passes because it had nothing to compare against looks the
#        same as one that compared and passed, and it did not.
#
# Setting CHECK_RATIOS_ALLOW_UNJUDGED=1 turns exit 3 into exit 0 for a caller
# that runs on a platform with no baseline yet and knows it. The last line
# still says UNJUDGED and names the variable, so the permission is visible in
# the log. It has no effect when anything was judged, and none on a failure.
#
# bench-state.json is regenerated by every benchmark run and is not tracked, so
# the recorded side has to be its own committed file; it cannot be "last run's
# bench-state.json".
#
# A parity kernel can run at two distinct speeds depending on the process, with
# nothing but code placement differing (bench/modes.awk has the detection rule).
# The gate still judges each ratio from the minimum over processes, which is the
# fast group whenever one process drew it, and so is not moved by how many did.
# What it no longer does is judge such a kernel silently: every split is printed
# under its kernel with the ratio the slow group alone would give, and listed
# again at the end. A median would have been worse here: it flips between the
# groups on the share of processes that drew each.

set -u

state_file="${1:-}"
baseline_file="${2:-}"
platform="${3:-}"

if [ -z "$state_file" ] || [ -z "$baseline_file" ] || [ -z "$platform" ]; then
    echo "Usage: $0 <bench-state.json> <ratio-baseline.json> <platform>" >&2
    exit 2
fi

for f in "$state_file" "$baseline_file"; do
    if [ ! -f "$f" ]; then
        echo "check-ratios: $f not found" >&2
        exit 2
    fi
done

# --- baseline ----------------------------------------------------------

threshold=$(sed -n 's/^ *"threshold": *\([0-9.]*\).*/\1/p' "$baseline_file" | head -1)
if [ -z "$threshold" ]; then
    echo "check-ratios: no \"threshold\" in $baseline_file" >&2
    exit 2
fi

# "<platform>/<key>": <number>   ->   <key><TAB><number>
baseline_ratios=$(sed -n "s|^ *\"$platform/\([^\"]*\)\": *\([0-9.]*\),\{0,1\}\$|\1\t\2|p" "$baseline_file")

# --- measured ----------------------------------------------------------

# "name": {... "ratio": <value> ...}   ->   name<TAB>value
# Entries whose ratio is null (a half that errored) are dropped here and
# reported as missing below rather than compared against nothing.
measured=$(sed -n 's/^ *"\([^"]*\)": {.*"ratio": *\([^,}]*\).*/\1\t\2/p' "$state_file" \
    | awk -F'\t' '$2 + 0 == $2 { print $1 "\t" $2 }')

parity_measured=$(echo "$measured" | awk -F'\t' '$1 ~ /^parity\// { print }')

if [ -z "$parity_measured" ]; then
    echo "check-ratios: no parity/* entries in $state_file -- the parity benchmark did not run." >&2
    exit 1
fi

# cl-bench rows are everything that is neither a parity row nor an allocation
# row (those are byte counts; their "ratio" is not a time ratio).
clbench_ratios=$(echo "$measured" \
    | awk -F'\t' '$1 !~ /^parity\// && $1 !~ /\/consed$/ { print $2 }' \
    | sort -g)

lookup_baseline() {
    echo "$baseline_ratios" | awk -F'\t' -v n="$1" '$1 == n { print $2; exit }'
}

# --- parity ------------------------------------------------------------

echo "=== parity ratios (platform: $platform, threshold: ${threshold}x baseline) ==="

# Per-process splits, as recorded by make-parity-state.sh (see bench/modes.awk):
#   name csharp_ms processes  cs_fast_n cs_fast_ms cs_slow_n cs_slow_ms
#                             d_fast_n  d_fast_ms  d_slow_n  d_slow_ms
# with "-" in the four fields of a side that is one group. A state file from
# before the split was recorded has no such fields and reads as unsplit.
split_rows=$(awk '
    function num(s, key,    r) {
        if (!match(s, "\"" key "\": *-?[0-9.]+")) return "-"
        r = substr(s, RSTART, RLENGTH); sub(/.*: */, "", r); return r
    }
    function obj(s, key) {
        if (!match(s, "\"" key "\": *[{][^}]*[}]")) return ""
        return substr(s, RSTART, RLENGTH)
    }
    function side(s) {
        if (s == "") return "-\t-\t-\t-"
        return num(s, "fast_n") "\t" num(s, "fast_ms") "\t" num(s, "slow_n") "\t" num(s, "slow_ms")
    }
    /^ *"parity\/[^"]*": [{]/ {
        name = $0; sub(/^ *"/, "", name); sub(/".*/, "", name)
        print name "\t" num($0, "csharp_ms") "\t" num($0, "processes") "\t" \
              side(obj($0, "csharp_split")) "\t" side(obj($0, "dotcl_split"))
    }' "$state_file")

processes=$(echo "$split_rows" | awk -F'\t' '$3 != "-" && (m == "" || $3 < m) { m = $3 } END { print m }')
if [ -n "$processes" ]; then
    if [ "$processes" -lt 3 ]; then
        echo "  ($processes process(es) per kernel: too few to check for a split; the check needs 3)"
    else
        echo "  ($processes processes per kernel; ratios use each side's minimum)"
    fi
fi

# split_note <name> <limit or empty>: one line per side that split, or nothing.
split_note() {
    echo "$split_rows" | awk -F'\t' -v n="$1" -v limit="$2" '
        $1 == n {
            c = $2
            if ($8 != "-") {
                slow = $11 / c
                printf "      SPLIT dotcl: %d of %d processes at %s ms, %d at %s ms (slow/fast %.2f).\n", \
                       $8, $8 + $10, $9, $10, $11, $11 / $9
                printf "        The ratio above is from the fast group; the slow group alone gives %.2f", slow
                if (limit != "") printf " (%s the limit)", (slow > limit + 0) ? "over" : "within"
                printf ".\n"
            }
            if ($4 != "-") {
                printf "      SPLIT C#: %d of %d processes at %s ms, %d at %s ms (slow/fast %.2f).\n", \
                       $4, $4 + $6, $5, $6, $7, $7 / $5
                printf "        The ratio above divides by the fast C# group.\n"
            }
        }'
}

failed=0
judged=0
unbaselined=0
not_judged=0
unbaselined_lines=""
split_kernels=""

while IFS=$'\t' read -r name ratio; do
    [ -z "$name" ] && continue
    base=$(lookup_baseline "$name")
    limit=""
    if [ -z "$base" ]; then
        unbaselined=$((unbaselined + 1))
        unbaselined_lines="$unbaselined_lines    \"$platform/$name\": $ratio,\n"
        printf '  %-28s %8s   (no baseline)\n' "$name" "$ratio"
    else
        judged=$((judged + 1))
        limit=$(awk "BEGIN { printf \"%.2f\", $base * $threshold }")
        if awk "BEGIN { exit !($ratio > $limit) }"; then
            printf '  %-28s %8s   FAIL  baseline %s, limit %s\n' "$name" "$ratio" "$base" "$limit"
            failed=$((failed + 1))
        else
            printf '  %-28s %8s   ok    baseline %s, limit %s\n' "$name" "$ratio" "$base" "$limit"
        fi
    fi
    note=$(split_note "$name" "$limit")
    if [ -n "$note" ]; then
        echo "$note"
        split_kernels="$split_kernels $name"
    fi
done <<< "$parity_measured"

# --- cl-bench median ---------------------------------------------------

echo "=== cl-bench ratio median ==="

clbench_count=$(echo "$clbench_ratios" | grep -c '[0-9]' || true)
clbench_base=$(lookup_baseline "cl-bench/median")

if [ "$clbench_count" -lt 20 ]; then
    # The cl-bench step runs under `|| true` on purpose: a missing or slow SBCL
    # is a data-collection problem, not a broken build. Keep that policy here,
    # but say out loud that the check did not happen.
    echo "  SKIPPED: only $clbench_count cl-bench ratios in $state_file (need 20)."
    not_judged=$((not_judged + 1))
elif [ -z "$clbench_base" ]; then
    median=$(echo "$clbench_ratios" | awk '{ v[NR] = $1 }
        END { if (NR % 2) printf "%.2f", v[(NR+1)/2]
              else printf "%.2f", (v[NR/2] + v[NR/2+1]) / 2 }')
    echo "  SKIPPED: no \"$platform/cl-bench/median\" baseline. Measured: $median over $clbench_count benchmarks."
    unbaselined=$((unbaselined + 1))
    unbaselined_lines="$unbaselined_lines    \"$platform/cl-bench/median\": $median,\n"
else
    median=$(echo "$clbench_ratios" | awk '{ v[NR] = $1 }
        END { if (NR % 2) printf "%.2f", v[(NR+1)/2]
              else printf "%.2f", (v[NR/2] + v[NR/2+1]) / 2 }')
    judged=$((judged + 1))
    limit=$(awk "BEGIN { printf \"%.2f\", $clbench_base * $threshold }")
    if awk "BEGIN { exit !($median > $limit) }"; then
        printf '  %-28s %8s   FAIL  baseline %s, limit %s (%s benchmarks)\n' \
            "cl-bench/median" "$median" "$clbench_base" "$limit" "$clbench_count"
        failed=$((failed + 1))
    else
        printf '  %-28s %8s   ok    baseline %s, limit %s (%s benchmarks)\n' \
            "cl-bench/median" "$median" "$clbench_base" "$limit" "$clbench_count"
    fi
fi

# --- verdict -----------------------------------------------------------

not_judged=$((not_judged + unbaselined))
total=$((judged + not_judged))

if [ "$unbaselined" -gt 0 ]; then
    echo ""
    echo "=== $unbaselined measurement(s) have no baseline for platform '$platform' ==="
    echo "These were measured but not checked. To start gating them, add these to"
    echo "the \"ratios\" object in bench/ratio-baseline.json and describe the machine"
    echo "under \"recorded\":"
    echo ""
    printf "$unbaselined_lines"
fi

split_count=$(echo $split_kernels | wc -w)
if [ "$split_count" -gt 0 ]; then
    echo ""
    echo "=== $split_count kernel(s) ran at two speeds depending on the process:$split_kernels ==="
    echo "The same code, split into a fast and a slow group of processes (code"
    echo "placement, not noise). Each ratio above is the fast group's, and the gate"
    echo "judged that. It could, because at least one process drew the fast group;"
    echo "a run in which every process draws the slow group shows one slow group"
    echo "and no split. A median over these processes would only count how many"
    echo "drew each group. See docs/profiling.md before reading anything more into it."
fi

if [ "$failed" -gt 0 ]; then
    echo ""
    echo "check-ratios: $failed measurement(s) above ${threshold}x their recorded baseline."
    echo "Either the change made them slower, or the baseline is stale, or -- for a"
    echo "kernel that can split -- every process drew the slow group this time."
    echo "See docs/profiling.md before editing bench/ratio-baseline.json."
    echo ""
    echo "check-ratios: FAIL -- $failed over the limit; $judged judged, $not_judged not judged"
    exit 1
fi

split_suffix=""
if [ "$split_count" -gt 0 ]; then
    split_suffix=" (with $split_count split kernel(s), above)"
fi

echo ""
if [ "$judged" -eq 0 ]; then
    echo "=== Nothing was judged ==="
    echo "Platform '$platform' has no baseline for any of the $total measurement(s)"
    echo "above, so this run compared nothing and cannot say whether anything got"
    echo "slower. It is reported as UNJUDGED, not ok."
    if [ -n "${GITHUB_ACTIONS:-}" ]; then
        echo "::warning title=check-ratios::UNJUDGED: 0 of $total measurement(s) judged; platform '$platform' has no baseline in bench/ratio-baseline.json"
    fi
    echo ""
    if [ "${CHECK_RATIOS_ALLOW_UNJUDGED:-}" = "1" ]; then
        echo "check-ratios: UNJUDGED -- 0 of $total measurement(s) judged, no baseline for '$platform' (exit 0 because CHECK_RATIOS_ALLOW_UNJUDGED=1)$split_suffix"
        exit 0
    fi
    echo "check-ratios: UNJUDGED -- 0 of $total measurement(s) judged, no baseline for '$platform' (exit 3; set CHECK_RATIOS_ALLOW_UNJUDGED=1 to accept)$split_suffix"
    exit 3
fi

if [ "$not_judged" -gt 0 ]; then
    if [ -n "${GITHUB_ACTIONS:-}" ]; then
        echo "::warning title=check-ratios::$not_judged of $total measurement(s) not judged on platform '$platform'"
    fi
    echo "check-ratios: ok -- $judged judged, $not_judged not judged$split_suffix"
else
    echo "check-ratios: ok -- $judged judged$split_suffix"
fi
exit 0
