#!/bin/sh
# Build contrib/quicklisp/quicklisp.lisp — the quicklisp client's components
# concatenated into one loadable file, the way asdf's make-asdf.sh produces a
# single asdf.lisp. The bundled .fasl is compiled from the result.
#
# Usage: scripts/build-quicklisp.sh <client-repo-root> <output-file>
set -e

src="$1/quicklisp"
out="$2"
prelude="$(dirname "$0")/quicklisp-prelude.lisp"
shims="$(dirname "$0")/quicklisp-compile-time-shims.lisp"
postlude="$(dirname "$0")/quicklisp-postlude.lisp"

for f in "$prelude" "$shims" "$postlude"; do
	[ -f "$f" ] || { echo "missing $f" >&2; exit 1; }
done

[ -f "$src/quicklisp.asd" ] || { echo "no quicklisp.asd under $src" >&2; exit 1; }

# Plain concatenation is equivalent to loading the system only because the
# system is :serial t. Fail loudly if that ever stops being true rather than
# emitting a file whose form order is meaningless.
grep -q ':serial *t' "$src/quicklisp.asd" || {
	echo "quicklisp.asd is no longer :serial t — concatenation order is unsafe" >&2
	exit 1
}

# Component order comes from the .asd rather than a hardcoded list so that an
# upstream file addition is picked up instead of silently dropped. Matched
# anywhere on the line, not at line start: the first component sits on the same
# line as ":components ((".
components=$(grep -oE '\(:file "[a-z0-9-]+"\)' "$src/quicklisp.asd" | sed -E 's/.*"(.+)".*/\1/')
[ -n "$components" ] || { echo "no (:file ...) components found in quicklisp.asd" >&2; exit 1; }

# Guard against the extraction silently dropping components: the number pulled
# out must equal the number of (:file occurrences in the .asd.
declared=$(grep -oE '\(:file "' "$src/quicklisp.asd" | wc -l | tr -d ' ')
extracted=$(echo "$components" | grep -c . | tr -d ' ')
[ "$declared" = "$extracted" ] || {
	echo "component extraction mismatch: .asd declares $declared, extracted $extracted" >&2
	exit 1
}

for name in $components; do
	[ -f "$src/$name.lisp" ] || { echo "missing component $name.lisp" >&2; exit 1; }
done

version=$(cat "$src/version.txt")
tmp="$out.tmp"

{
	echo ";;;; Generated by scripts/build-quicklisp.sh — do not edit."
	echo ";;;; quicklisp client components, concatenated in quicklisp.asd :serial order."
	echo ";;;; Source: dotcl/quicklisp-client, branch dotcl-support."
	echo ""
	echo ";;;; ---------------- dotcl prelude ----------------"
	cat "$prelude"
	echo ""
	# quicklisp.asd defines ql-info before its defsystem; the defsystem itself
	# is not part of the bundle. The version is folded in as a literal because
	# the original reads version.txt relative to *load-truename*, which does not
	# survive concatenation.
	echo "(defpackage #:ql-info (:export #:*version*))"
	echo "(defvar ql-info:*version* \"$version\")"
	echo ""
	for name in $components; do
		echo ";;;; ---------------- $name.lisp ----------------"
		cat "$src/$name.lisp"
		echo ""
		# The shims need the client's packages to exist (they bind a variable in
		# ql-impl) and must precede every component that macroexpands against
		# them, so they go directly after package.lisp.
		if [ "$name" = "package" ]; then
			echo ";;;; ---------------- dotcl compile-time shims ----------------"
			cat "$shims"
			echo ""
		fi
	done
	echo ";;;; ---------------- dotcl postlude ----------------"
	cat "$postlude"
} > "$tmp"

# cmp-then-mv so an unchanged rebuild does not bump mtime and cascade an
# unnecessary fasl rebuild (same reasoning as setup-asdf's cmp-then-cp).
if cmp -s "$tmp" "$out" 2>/dev/null; then
	rm -f "$tmp"
else
	mv "$tmp" "$out"
fi
