;;;; Extra shapes for the random integer form generator.
;;;;
;;;; pfdietz's generator (random-int-form.lsp) builds integer forms from integer
;;;; operations, binding forms and control transfer. The shapes below add parts
;;;; of the compiler it does not reach, while every form still returns an
;;;; integer so that the in-implementation check and the replay keep working:
;;;;   - double-float and single-float arithmetic and mixed float/integer
;;;;     comparison, converted back with FLOOR / ROUND / TRUNCATE
;;;;   - strings built from integers (PRINC-TO-STRING, FORMAT ~B ~36R)
;;;;   - specialized and general vectors, 2-D arrays, SVREF of VECTOR
;;;;   - multiple values (MULTIPLE-VALUE-BIND, NTH-VALUE, MULTIPLE-VALUE-CALL)
;;;;   - non-local exits out of closures, mapping functions, LOOP and
;;;;     UNWIND-PROTECT
;;;;   - &optional / &rest / &key local functions and APPLY, hash tables,
;;;;     places (INCF, PUSH, GETF, ROTATEF), conditions and restarts,
;;;;     characters, LET with float and small integer type declarations
;;;;
;;;; Loading this file wraps MAKE-RANDOM-INTEGER-FORM: with probability
;;;; cl-user::*rf-extra-rate* a form of size 4 or more is one of these shapes,
;;;; whose operands come from the generator again.
;;;;
;;;; Operands of float shapes are clamped to +-2^50 first, so that a nested
;;;; product stays far below the single-float range on every implementation.

(in-package :cl-test)

(defvar cl-user::*rf-extra-rate* 0.15)

(load "test/random/extra-defs.lisp")

(defvar *rf-original-make-random-integer-form*
  (fdefinition 'make-random-integer-form))

(defun rf-clamp (form)
  `(max -1125899906842624 (min 1125899906842624 ,form)))

(defun rf-parts (size n)
  (mapcar #'make-random-integer-form (random-partition (max n (- size 2)) n)))

(defun rf-float-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (let* ((fmt (random-from-seq #(1d0 1f0)))
           (fx `(float ,(rf-clamp x) ,fmt))
           (fy `(float ,(rf-clamp y) ,(random-from-seq #(1d0 1f0)))))
      (rcase
        (3 `(,(random-from-seq #(floor ceiling truncate round))
             (,(random-from-seq #(+ - *)) ,fx ,fy)))
        (2 `(truncate (/ ,fx (float (max 1 (abs ,(rf-clamp y))) ,fmt))))
        (2 `(if (,(random-from-seq #(< <= = /= > >=)) ,fx ,fy) 1 0))
        (2 `(if (,(random-from-seq #(< = >)) ,fx ,(rf-clamp y)) 1 0))
        (1 `(round (* ,(random-from-seq #(0.5d0 0.5f0 1.5d0 -0.5d0)) ,(rf-clamp x))))
        (1 `(nth-value 0 (floor ,fx ,(random-from-seq #(2 3 0.25d0 7.5f0)))))
        (1 `(let ((xf ,fx)) (declare (type ,(if (eql fmt 1d0) 'double-float 'single-float) xf))
              (truncate (+ xf xf))))))))

(defun rf-string-form (size)
  (destructuring-bind (x) (rf-parts size 1)
    (rcase
      (2 `(length (princ-to-string ,x)))
      (2 `(parse-integer (princ-to-string ,x)))
      (1 `(char-code (char (format nil "~36R" ,x) 0)))
      (1 `(count #\1 (format nil "~B" (abs ,x))))
      (1 `(or (position #\5 (princ-to-string ,x)) -1))
      (1 `(let ((xs (make-string 3 :initial-element #\a)))
            (setf (char xs 1) (code-char (+ 48 (mod ,x 10))))
            (digit-char-p (char xs 1)))))))

(defun rf-array-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (let ((n (1+ (random 5))))
      (multiple-value-bind (et val)
          (rcase
            (2 (values t x))
            (1 (values '(unsigned-byte 8) `(ldb (byte 8 0) ,x)))
            (1 (values '(signed-byte 32) `(- (ldb (byte 32 0) ,x) 2147483648)))
            (1 (values 'bit `(logand ,x 1))))
        (rcase
          (3 `(let ((xv (make-array ,n :element-type ',et :initial-element 0)))
                (setf (aref xv (mod ,y ,n)) ,val)
                (reduce #'+ xv)))
          (1 `(let ((xv (make-array ,n :element-type ',et :initial-element 0)))
                (dotimes (xi ,n) (setf (aref xv xi) ,val))
                (aref xv ,(random n))))
          (1 `(let ((xa (make-array '(2 3) :initial-element ,x)))
                (setf (aref xa 1 (mod ,y 3)) 0)
                (+ (aref xa 0 0) (aref xa 1 2))))
          (1 `(svref (vector ,x ,y 0) (mod ,y 3))))))))

(defun rf-mv-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (let ((op (random-from-seq #(floor ceiling truncate round))))
      (rcase
        (2 `(multiple-value-bind (xq xr) (,op ,x (max 1 ,y)) (+ xq xr)))
        (1 `(nth-value 1 (,op ,x (max 1 ,y))))
        (1 `(multiple-value-call #'+ (,op ,x 7) (values ,y ,z)))
        (1 `(car (multiple-value-list (values ,x ,y))))
        (1 `(apply #'+ (multiple-value-list (,op ,x 3))))
        (1 `(multiple-value-bind (xa xb xc) (values ,x ,y) (+ xa (or xb 0) (or xc 1))))
        (1 `(let ((xr (multiple-value-list (if (> ,z 0) (values ,x ,y) (values ,y)))))
              (+ (length xr) (car xr))))))))

(defun rf-exit-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (2 `(block bx (+ ,x (if (> ,y 0) (return-from bx ,z) 0))))
      (2 `(block bx (funcall (lambda () (return-from bx ,x))) ,y))
      (1 `(catch 'cx (+ ,x (throw 'cx ,y))))
      (2 `(block bx (mapc (lambda (xe) (when (> xe ,z) (return-from bx xe))) (list ,x ,y)) 0))
      (1 `(loop for xe in (list ,x ,y) when (> xe ,z) return xe finally (return 0)))
      (1 `(block bx (unwind-protect (return-from bx ,x) ,y)))
      (1 `(let ((xacc 0)) (block bx (unwind-protect (return-from bx ,x) (setq xacc ,y))) xacc))
      (1 `(dolist (xe (list ,x ,y) ,z) (when (< xe 0) (return xe)))))))

(defun rf-call-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (2 `(flet ((xg (xp &optional (xq ,y) &rest xr &key (xk 0) &allow-other-keys)
                   (+ xp xq (length xr) xk)))
            ,(rcase (1 `(xg ,x)) (1 `(xg ,x ,z)) (1 `(xg ,x ,z :xk ,y))
                    (1 `(apply #'xg ,x (list ,z :xk ,y :other 1))))))
      (1 `(labels ((xg (xn xacc) (if (<= xn 0) xacc (xg (1- xn) (+ xacc ,z)))))
            (xg (mod ,x 5) ,y)))
      (1 `(funcall (lambda (&rest xr) (reduce #'+ xr)) ,x ,y ,z))
      (1 `(let ((xfn (if (> ,z 0) #'+ #'-))) (funcall xfn ,x ,y))))))

(defun rf-place-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (2 `(let ((xh (make-hash-table)))
            (setf (gethash ,x xh) ,y)
            (incf (gethash (mod ,z 3) xh 0) 5)
            (+ (gethash ,x xh 0) (hash-table-count xh))))
      (1 `(let ((xh (make-hash-table :test 'equal))
                (xs (princ-to-string ,x)))
            (setf (gethash xs xh) ,y)
            (gethash (copy-seq xs) xh 0)))
      (2 `(let ((xl (list ,x ,y)))
            (incf (car xl) ,z)
            (push ,z (cdr xl))
            (apply #'+ xl)))
      (1 `(let ((xpl (list :a ,x :b ,y)))
            (setf (getf xpl :b) ,z)
            (incf (getf xpl :c 0))
            (+ (getf xpl :a) (getf xpl :b) (getf xpl :c))))
      (1 `(let ((xv (vector ,x ,y)))
            (rotatef (aref xv 0) (aref xv 1))
            (- (aref xv 0) (aref xv 1)))))))

(defun rf-condition-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (2 `(handler-case (if (> ,x ,y) (error "e") ,z) (error () ,y)))
      (1 `(handler-case (truncate ,x (- ,y ,y)) (division-by-zero () ,z)))
      (1 `(or (ignore-errors (parse-integer (format nil "~Dx" ,x))) ,y))
      (1 `(block bx (handler-bind ((error (lambda (xc) (declare (ignore xc)) (return-from bx ,y))))
                      (+ ,x (if (> ,z 0) (error "e") 0)))))
      (1 `(restart-case (+ ,x (if (> ,z 0) (invoke-restart 'xrs ,y) 0))
            (xrs (v) v))))))

(defun rf-char-typed-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (rcase
      (1 `(char-code (char-upcase (code-char (+ 97 (mod ,x 26))))))
      (1 `(digit-char-p (digit-char (mod ,x 10))))
      (1 `(if (char< (code-char (+ 65 (mod ,x 26))) (code-char (+ 65 (mod ,y 26)))) 1 0))
      (1 `(let ((xd (float ,(rf-clamp x) 1d0)))
            (declare (type double-float xd))
            (floor (* xd 3) 7)))
      (1 `(let ((xn (ldb (byte 16 0) ,x)))
            (declare (type (unsigned-byte 16) xn))
            (+ (* xn xn) ,y)))
      (1 `(let ((xn (- (ldb (byte 30 0) ,x) 536870912)))
            (declare (type (signed-byte 30) xn))
            (- (ash xn 2) xn))))))

(defun rf-clos-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (2 `(rf-gf (make-instance 'rf-pt3 :x ,x :y ,y) ,z))
      (1 `(rf-gf (make-instance 'rf-pt :x ,x) 0))
      (1 `(rf-gf ,x 0))
      (2 `(let ((xo (make-instance 'rf-pt :x ,x)))
            (setf (rf-pt-y xo) ,y)
            (incf (slot-value xo 'x) ,z)
            (rf-gf xo 0)))
      (1 `(with-slots (x y) (make-instance 'rf-pt :x ,x :y ,y) (setq x (+ x 1)) (- x y)))
      (1 `(with-accessors ((xx rf-pt-x)) (make-instance 'rf-pt3 :x ,x) (incf xx ,y) xx))
      (1 `(rf-gf2 ,x))
      (1 `(+ (rf-gf2 (/ ,x 2)) (rf-gf2 (list ,y))))
      (1 `(if (typep (make-instance 'rf-pt3 :x ,x) 'rf-pt) (slot-value (make-instance 'rf-pt3 :z ,y) 'z) ,z))
      (2 `(let ((xs (make-rf-s :a ,x :b ,y)))
            (incf (rf-s-a xs) ,z)
            (+ (rf-s-a xs) (rf-s-b (copy-rf-s xs)))))
      (1 `(rf-s-a (make-rf-s :a (if (rf-s-p (make-rf-s)) ,x ,y)))))))

(defun rf-cond2-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (2 `(handler-case (error 'rf-cond :v ,x) (rf-cond (xc) (rf-cond-v xc))))
      (1 `(handler-case (if (> ,z 0) (error 'rf-cond :v ,x) ,y) (error (xc) (rf-cond-v xc))))
      (2 `(block bx (handler-bind ((rf-cond (lambda (xc) (return-from bx (rf-cond-v xc)))))
                      (signal 'rf-cond :v ,x)
                      ,y)))
      (1 `(handler-bind ((rf-cond (lambda (xc) (invoke-restart 'use-value (rf-cond-v xc)))))
            (restart-case (error 'rf-cond :v ,x)
              (use-value (xv) (+ xv ,y)))))
      (1 `(restart-case (progn (invoke-restart 'xr2 ,x) ,y)
            (xr1 () ,z)
            (xr2 (xv) (* 2 xv))))
      (1 `(let ((xn 0))
            (handler-bind ((warning (lambda (xc) (incf xn) (muffle-warning xc))))
              (warn "w") (when (> ,x 0) (warn "w")))
            (+ xn ,y)))
      (1 `(or (ignore-errors (rf-cond-v (make-condition 'rf-cond :v ,x))) ,y))
      (1 `(catch 'xt (handler-case (throw 'xt ,x) (error () ,y)))))))

(defun rf-format-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(length (format nil "~R" (mod ,x 100000))))
      (1 `(length (format nil "~@R" (1+ (mod ,x 3999)))))
      (1 `(parse-integer (format nil "~8,'0D" (abs ,x))))
      (1 `(length (format nil "~:D" ,x)))
      (1 `(length (format nil "~{~A~^,~}" (list ,x ,y ,z))))
      (1 `(parse-integer (format nil "~X" ,x) :radix 16))
      (1 `(parse-integer (format nil "~36R" ,x) :radix 36))
      (1 `(length (format nil "~,2F" (/ (mod ,x 100000) 7))))
      (1 `(length (format nil "~E" (float (mod ,x 1000) 1d0))))
      (1 `(length (format nil "~10@A" ,x)))
      (1 `(count #\space (format nil "~10A" (mod ,x 1000))))
      (1 `(length (format nil "~[zero~;one~:;many~]" (mod ,x 4))))
      (1 `(length (format nil "~:[no~;yes~]" (> ,x ,y))))
      (1 `(length (format nil "~@{~D~^ ~}" ,x ,y)))
      (1 `(length (format nil "~5,'*D|~v,'0D" ,x (mod ,y 8) ,z))))))

(defun rf-loop-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(loop for xi from 0 below (mod ,x 10) sum (* xi ,y)))
      (1 `(loop for xe in (list ,x ,y ,z) maximize xe))
      (1 `(loop for xi below 5 collect (+ xi ,x) into xl finally (return (reduce #'+ xl))))
      (1 `(loop for xe across (vector ,x ,y) count (> xe ,z)))
      (1 `(loop with xs = 0 for xi from 1 to 3 do (incf xs (* xi ,x)) finally (return xs)))
      (1 `(loop for (xa xb) on (list ,x ,y ,z) by #'cddr sum (+ xa (or xb 0))))
      (1 `(or (loop for xi from 1 to 4 thereis (and (> xi (mod ,x 5)) xi)) 0))
      (1 `(loop for xi downfrom 3 to 0 for xe = ,x then (- xe xi) finally (return xe)))
      (1 `(loop for xi from 0 to 2 minimize (- ,y xi) into xm finally (return xm)))
      (1 `(loop for xe in (list ,x ,y ,z) when (evenp xe) sum xe into xs else count t into xc
                finally (return (+ xs xc))))
      (1 `(loop named xn for xi from 0 do (when (> xi (mod ,x 7)) (return-from xn xi)))))))

(defun rf-string2-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (rcase
      (1 `(or (search "1" (princ-to-string ,x)) -1))
      (1 `(length (concatenate 'string (princ-to-string ,x) "-" (princ-to-string ,y))))
      (1 `(or (string< (princ-to-string ,x) (princ-to-string ,y)) -1))
      (1 `(or (mismatch (princ-to-string ,x) (princ-to-string ,y)) -1))
      (1 `(count #\1 (remove #\- (princ-to-string ,x))))
      (1 `(length (string-trim "-0" (princ-to-string ,x))))
      (1 `(parse-integer (reverse (princ-to-string (abs ,x)))))
      (1 `(parse-integer (substitute #\9 #\1 (princ-to-string ,x))))
      (1 `(char-code (char (string-downcase (format nil "~36R" (abs ,x))) 0)))
      (1 `(length (subseq (princ-to-string ,x) (min 1 (length (princ-to-string ,x))))))
      (1 `(let ((xs (make-array 0 :element-type 'character :adjustable t :fill-pointer 0)))
            (vector-push-extend #\4 xs)
            (loop for xc across (princ-to-string (abs ,x)) do (vector-push-extend xc xs))
            (parse-integer xs)))
      (1 `(length (with-output-to-string (xo) (princ ,x xo) (write-string "ab" xo))))
      (1 `(let ((xs (copy-seq "abcdef"))) (setf (subseq xs 1 3) (princ-to-string (mod ,x 100)))
            (char-code (char xs 2))))
      (1 `(if (string-equal (string-upcase "xYz") "XYZ") ,x ,y)))))

(defun rf-hash2-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(let ((xh (make-hash-table :test 'equalp)))
            (setf (gethash "Ab" xh) ,x)
            (+ (gethash "aB" xh 0) (gethash "c" xh ,y))))
      (1 `(let ((xh (make-hash-table)) (xs 0))
            (dotimes (xi 5) (setf (gethash xi xh) (* xi ,x)))
            (remhash 2 xh)
            (maphash (lambda (xk xv) (incf xs (+ xk xv))) xh)
            (+ xs (hash-table-count xh))))
      (1 `(let ((xh (make-hash-table :test 'equal)))
            (setf (gethash (list ,x) xh) ,y)
            (multiple-value-bind (xv xp) (gethash (list ,x) xh) (if xp xv ,z))))
      (1 `(let ((xh (make-hash-table)))
            (setf (gethash 1 xh) ,x (gethash 2 xh) ,y)
            (loop for xk being the hash-keys of xh using (hash-value xv) sum (* xk xv))))
      (1 `(let ((xh (make-hash-table)) (xn 0))
            (setf (gethash ,x xh) 1 (gethash ,y xh) 2)
            (with-hash-table-iterator (xg xh)
              (loop (multiple-value-bind (xm xk xv) (xg)
                      (declare (ignore xk))
                      (unless xm (return))
                      (incf xn xv))))
            xn))
      (1 `(let ((xh (make-hash-table :test 'eql)) (xk ,x))
            (incf (gethash xk xh 0) ,y)
            (incf (gethash xk xh 0) ,z)
            (gethash xk xh))))))

(defun rf-macro-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(macrolet ((xm (a b) `(+ ,a (* 2 ,b)))) (xm ,x ,y)))
      (1 `(symbol-macrolet ((xs (+ ,x 1))) (* xs 2)))
      (1 `(destructuring-bind (xa (xb &optional (xc 5)) &rest xr) (list ,x (list ,y) ,z)
            (+ xa xb xc (length xr))))
      (1 `(destructuring-bind (&key (xa 1) (xb ,y)) (list :xa ,x) (- xa xb)))
      (1 `(let ((xv (list ,x ,y))) (destructuring-bind (xa &rest xb) xv (+ xa (car xb)))))
      (1 `(funcall (lambda (xa &aux (xb (* 2 xa))) (+ xa xb)) ,x))
      (1 `(typecase ,x ((integer 0 100) (+ 1 ,y)) (integer ,z) (t 0)))
      (1 `(etypecase (if (> ,x ,y) (list ,z) ,z) (cons (car (if (> ,x ,y) (list ,z) (list 0)))) (integer 7)))
      (1 `(case (mod ,x 4) ((0 1) ,y) (2 ,z) (otherwise -1)))
      (1 `(let ((xa ,x) (xb ,y)) (psetq xa xb xb xa) (- xa xb)))
      (1 `(let ((xa ,x) (xb ,y)) (multiple-value-setq (xa xb) (floor xa (max 1 (abs xb)))) (+ xa xb)))
      (1 `(let ((xa ,x) (xb ,y) (xc ,z)) (rotatef xa xb xc) (shiftf xa xb (+ xc 1)) (+ xa xb xc))))))

(defun rf-seq-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(reduce #'+ (sort (list ,x ,y ,z) #'<) :key #'abs :initial-value 1))
      (1 `(car (stable-sort (list ,x ,y ,z (- ,x)) #'> :key (lambda (xe) (mod xe 7)))))
      (1 `(length (remove-duplicates (list ,x ,y ,z ,x) :test #'=)))
      (1 `(reduce #'max (map 'vector #'+ (list ,x ,y) (vector ,z 1 2))))
      (1 `(let ((xv (make-array 3 :initial-element 0))) (map-into xv #'- (list ,x ,y ,z)) (aref xv 2)))
      (1 `(or (position-if (lambda (xe) (> xe ,z)) (list ,x ,y)) -1))
      (1 `(or (car (find ,x (list (list ,y) (list ,x)) :key #'car)) -1))
      (1 `(let ((xv (vector 1 2 3 4))) (replace xv (list ,x ,y) :start1 1) (reduce #'+ xv)))
      (1 `(let ((xv (make-list 4 :initial-element ,x))) (fill xv ,y :start 2) (reduce #'- xv)))
      (1 `(car (merge 'list (list ,x 5) (list ,y 3) #'<)))
      (1 `(count-if #'oddp (nreverse (list ,x ,y ,z))))
      (1 `(reduce #'+ (subseq (vector ,x ,y ,z) 1) :from-end t))
      (1 `(let ((xl (list ,x ,y ,z))) (length (delete ,x xl))))
      (1 `(count 1 (bit-and #*1011 (if (> ,x ,y) #*1101 #*0111))))
      (1 `(apply #'+ (mapcan (lambda (xe) (if (> xe 0) (list xe) nil)) (list ,x ,y ,z))))
      (1 `(or (search (list ,y) (list ,x ,y ,z)) -1)))))

(defun rf-array2-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(let ((xv (make-array 2 :adjustable t :fill-pointer 0)))
            (vector-push-extend ,x xv) (vector-push-extend ,y xv) (vector-push-extend ,z xv)
            (+ (fill-pointer xv) (aref xv 2))))
      (1 `(let ((xv (adjust-array (make-array 2 :adjustable t :initial-element ,x) 4 :initial-element ,y)))
            (+ (aref xv 1) (aref xv 3))))
      (1 `(let* ((xa (make-array 6 :initial-element 0))
                 (xd (make-array 3 :displaced-to xa :displaced-index-offset 2)))
            (setf (aref xd 1) ,x) (aref xa 3)))
      (1 `(let ((xa (make-array '(2 3) :element-type '(signed-byte 32) :initial-element 0)))
            (declare (type (simple-array (signed-byte 32) (2 3)) xa))
            (setf (aref xa 1 2) (mod ,x 1000) (row-major-aref xa 0) (mod ,y 1000))
            (+ (aref xa 1 2) (aref xa 0 0) (array-total-size xa))))
      (1 `(let ((xv (make-array 3 :element-type '(signed-byte 64) :initial-element 0)))
            (declare (type (simple-array (signed-byte 64) (3)) xv))
            (setf (aref xv 0) (mod ,x 1000000) (aref xv 1) (- (mod ,y 1000000)))
            (loop for xe across xv sum xe)))
      (1 `(let ((xv (make-array 4 :element-type 'double-float :initial-element 1d0)))
            (setf (aref xv (mod ,x 4)) (float (mod ,y 1000) 1d0))
            (floor (reduce #'+ xv))))
      (1 `(let ((xv (make-array 3 :initial-contents (list ,x ,y ,z))))
            (+ (array-dimension xv 0) (svref xv (mod ,x 3))))))))

(defun rf-closure-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(let ((xn ,x)) (let ((xf (lambda () (incf xn ,y)))) (funcall xf) (funcall xf) xn)))
      (1 `(let ((xfs (loop for xi below 3 collect (let ((xj xi)) (lambda () (* xj ,x))))))
            (reduce #'+ (mapcar #'funcall xfs))))
      (1 `(labels ((xev (xn) (if (<= xn 0) t (xod (1- xn)))) (xod (xn) (if (<= xn 0) nil (xev (1- xn)))))
            (if (xev (mod ,x 20)) ,y ,z)))
      (1 `(flet ((xf (xa) (* xa 3))) (declare (inline xf)) (+ (xf ,x) (xf ,y))))
      (1 `(labels ((xf (xa xacc) (declare (type (integer 0 100) xacc)) (if (<= xa 0) xacc (xf (1- xa) (+ xacc 2)))))
            (+ (xf (mod ,x 30) 0) ,y)))
      (1 `(let ((xf (lambda (xa) (+ xa ,z)))) (declare (dynamic-extent xf)) (funcall xf ,x)))
      (1 `(let ((*s1* ,x)) (declare (special *s1*)) (funcall (lambda () *s1*))))
      (1 `(let ((xc 0)) (tagbody xl (incf xc) (when (< xc (mod ,x 5)) (go xl))) (+ xc ,y)))
      (1 `(let ((xa ,x)) (declare (type integer xa)) (the integer (+ xa (the integer ,y))))))))

(defun rf-number-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (rcase
      (1 `(floor (* (/ ,x 3) (/ ,y 7)) 5))
      (1 `(numerator (/ ,x (max 1 (abs ,y)))))
      (1 `(denominator (+ (/ ,x 6) (/ ,y 10))))
      (1 `(floor (expt (/ ,x (max 1 (abs ,y))) 2)))
      (1 `(realpart (* (complex ,x 1) (complex 2 ,y))))
      (1 `(imagpart (+ (complex ,x ,y) (complex 1 -1))))
      (1 `(isqrt (abs (* ,x ,y))))
      (1 `(integer-length (* ,x ,y)))
      (1 `(round (/ (+ ,x ,y) 2)))
      (1 `(mod (- ,x) (if (zerop ,y) 3 ,y)))
      (1 `(rem (* ,x ,x) (if (zerop ,y) 7 ,y)))
      (1 `(if (= (/ ,x 2) (* ,x 1/2)) 1 0))
      (1 `(logcount (logxor ,x (ash ,y -3))))
      (1 `(ldb (byte 8 (mod ,x 60)) ,y))
      (1 `(if (< (/ ,x 3) (/ ,y 3)) 1 0)))))

(defun rf-print-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (rcase
      (1 `(read-from-string (prin1-to-string ,x)))
      (1 `(floor (read-from-string (prin1-to-string (float (mod ,x 100000) 1d0)))))
      (1 `(floor (* 1000 (read-from-string (prin1-to-string (/ (mod ,x 1000) 8.0))))))
      (1 `(length (prin1-to-string (/ ,x (max 1 (abs ,y))))))
      (1 `(length (write-to-string ,x :base 7 :radix t)))
      (1 `(parse-integer (write-to-string ,x :base 16) :radix 16))
      (1 `(read-from-string (format nil "#x~X" (abs ,x))))
      (1 `(let ((xpv (abs ,x))) (let ((*print-base* 2)) (length (princ-to-string xpv)))))
      (1 `(length (format nil "~S" (list ,x "a" #\b))))
      (1 `(length (prin1-to-string (float (/ (mod ,x 100000) 7) 1d0))))
      (1 `(with-input-from-string (xs (format nil "~D ~D" ,x ,y)) (+ (read xs) (read xs))))
      (1 `(multiple-value-bind (xv xp) (read-from-string (format nil "~D  " ,x)) (+ xv xp))))))

(defun rf-clos2-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (rcase
      (1 `(rf-gf3 (mod ,x 3)))
      (1 `(rf-gf3 (list ,x ,y)))
      (1 `(let ((xo (make-instance 'rf-cnt :k (mod ,x 5)))) (rf-step xo ,y) (rf-cnt-n xo)))
      (1 `(funcall #'rf-gf3 (if (> ,x ,y) 0 (list 1))))
      (1 `(apply #'rf-gf (list ,x ,y)))
      (1 `(reduce #'+ (mapcar #'rf-gf3 (list ,x 0 (list ,y)))))
      (1 `(let ((xo (make-instance 'rf-cnt))) (dotimes (xi 3) (rf-step xo ,x)) (rf-cnt-n xo)))
      (1 `(if (slot-boundp (make-instance 'rf-cnt) 'k) ,x ,y)))))

(defun rf-slots-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(let ((xo (make-instance 'rf-box :v ,x)))
            (with-slots (v w) xo (incf v ,y) (setf w (- v w)))
            (+ (rf-box-v xo) (rf-box-w xo))))
      (1 `(let ((xo (make-instance 'rf-box :w ,x)))
            (with-accessors ((xv rf-box-v) (xw rf-box-w)) xo
              (setf xv ,y) (incf xw xv) (rotatef xv xw))
            (- (rf-box-v xo) (rf-box-w xo))))
      (1 `(let ((xa (make-instance 'rf-box :v ,x)) (xb (make-instance 'rf-box :v ,y)))
            (with-slots ((xva v)) xa (with-slots ((xvb v)) xb (psetf xva xvb xvb xva)))
            (- (rf-box-v xa) (rf-box-v xb))))
      (1 `(let ((xo (make-instance 'rf-box)))
            (setf (slot-value xo (if (> ,x ,y) 'v 'w)) ,z)
            (+ (slot-value xo 'v) (slot-value xo 'w))))
      (1 `(let ((xo (make-instance 'rf-box :v ,x)))
            (with-slots (v) xo (let ((xf (lambda () (incf v ,z)))) (funcall xf) (funcall xf)))
            (rf-box-v xo))))))

(defun rf-restart2-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(handler-bind ((rf-cond (lambda (xc) (declare (ignore xc)) nil)))
            (handler-case (error 'rf-cond :v ,x) (rf-cond (xc) (+ (rf-cond-v xc) ,y)))))
      (1 `(block bx
            (handler-bind ((error (lambda (xc) (let ((xr (find-restart 'xr1 xc))) (if xr (invoke-restart xr ,y) (return-from bx ,z))))))
              (restart-case (error 'rf-cond :v ,x) (xr1 (xv) (* 2 xv))))))
      (1 `(or (with-simple-restart (xsr "skip") (if (> ,x ,y) (invoke-restart 'xsr) ,z)) -1))
      (1 `(if (nth-value 1 (with-simple-restart (xsr "skip") (if (> ,x ,y) (invoke-restart 'xsr) ,z))) 1 0))
      (1 `(handler-bind ((error (lambda (xc) (declare (ignore xc)) (invoke-restart 'continue))))
            (+ ,x (progn (cerror "go on" "c ~D" ,y) ,z))))
      (1 `(handler-bind ((error (lambda (xc) (store-value (+ ,y 1) xc))))
            (restart-case (error "e") (store-value (xv) xv))))
      (1 `(let ((xn 0))
            (handler-bind ((rf-note (lambda (xc) (incf xn (rf-note-v xc)))))
              (handler-bind ((rf-note (lambda (xc) (declare (ignore xc)) (incf xn 1000))))
                (signal 'rf-note :v ,x)))
            xn))
      (1 `(restart-case (handler-bind ((error (lambda (xc) (declare (ignore xc)) (invoke-restart 'xr2 ,x))))
                          (restart-case (error "e") (xr1 () ,y)))
            (xr2 (xv) (+ xv ,z))))
      (1 `(restart-case (progn (invoke-restart (find-restart 'xr3)) ,x)
            (xr3 () :test (lambda (xc) (declare (ignore xc)) t) ,y)))
      (1 `(restart-case (let ((xrs (compute-restarts)))
                          (invoke-restart (find 'xr4 xrs :key #'restart-name) ,x))
            (xr4 (xv) (+ xv ,y))))
      (1 `(block bx (handler-bind ((rf-note (lambda (xc) (return-from bx (rf-note-v xc)))))
                      (+ ,y (or (signal 'rf-note :v ,x) 0))))))))

(defun rf-array3-form (size)
  (destructuring-bind (x y z) (rf-parts size 3)
    (rcase
      (1 `(let ((xa (make-array '(2 3 4) :initial-element ,x)))
            (setf (aref xa 1 2 3) ,y)
            (+ (aref xa 1 2 3) (array-row-major-index xa 1 2 3) (aref xa 0 0 0))))
      (1 `(let* ((xa (make-array '(3 4) :initial-element 0))
                 (xd (make-array 6 :displaced-to xa :displaced-index-offset 3)))
            (setf (aref xd 2) ,x) (+ (aref xa 1 1) (length xd))))
      (1 `(let* ((xv (make-array 12 :initial-element ,x))
                 (xa (make-array '(3 4) :displaced-to xv)))
            (setf (aref xa 2 1) ,y) (+ (aref xv 9) (array-rank xa))))
      (1 `(let* ((xa (make-array '(2 2) :adjustable t :initial-element ,x))
                 (xb (adjust-array xa '(3 3) :initial-element ,y)))
            (+ (aref xb 1 1) (aref xb 2 2))))
      (1 `(let* ((xv (make-array 10 :initial-element 0))
                 (xd (make-array 5 :displaced-to xv :displaced-index-offset 2)))
            (multiple-value-bind (xt xo) (array-displacement xd) (+ xo (length xt)))))
      (1 `(let* ((xv (make-array 10 :initial-element ,z))
                 (xd1 (make-array 6 :displaced-to xv :displaced-index-offset 2))
                 (xd2 (make-array 3 :displaced-to xd1 :displaced-index-offset 1)))
            (setf (aref xd2 0) ,x) (aref xv 3)))
      (1 `(let ((xa (make-array '(2 3) :element-type 'bit :initial-element 0)))
            (setf (aref xa 1 (mod ,x 3)) 1) (+ (aref xa 1 (mod ,x 3)) (array-total-size xa))))
      (1 `(let ((xa (make-array '(2 2) :initial-contents (list (list ,x ,y) (list ,z 1)))))
            (reduce #'+ (make-array 4 :displaced-to xa)))))))

(defun rf-stream-form (size)
  (destructuring-bind (x y) (rf-parts size 2)
    (rcase
      (1 `(length (with-output-to-string (xo) (format xo "~D|~A" ,x ,y) (terpri xo))))
      (1 `(let ((xo (make-string-output-stream)))
            (write-string "abc" xo) (princ ,x xo)
            (let ((xs1 (get-output-stream-string xo)))
              (princ ,y xo)
              (+ (length xs1) (length (get-output-stream-string xo))))))
      (1 `(with-input-from-string (xi (format nil "~D ~D" ,x ,y) :start 0)
            (- (read xi) (read xi))))
      (1 `(with-input-from-string (xi (format nil "~D~%~D" ,x ,y))
            (+ (length (read-line xi)) (length (read-line xi nil "")))))
      (1 `(with-input-from-string (xi (princ-to-string ,x))
            (let ((xc (read-char xi))) (unread-char xc xi) (char-code (peek-char nil xi)))))
      (1 `(let ((xs (make-string-input-stream (princ-to-string ,x) 1)))
            (length (read-line xs nil ""))))
      (1 `(length (with-output-to-string (xo) (write-string (princ-to-string ,x) xo :start 1))))
      (1 `(let ((xi (make-string-input-stream (format nil "~D" (abs ,x)))) (xn 0))
            (loop for xc = (read-char xi nil) while xc do (incf xn (digit-char-p xc)))
            xn))
      (1 `(let ((xp 0)) (with-input-from-string (xi "abcdef" :index xp :start (mod ,x 3)) (read-char xi)) xp)))))

(defun rf-printvar-form (size)
  ;; The operands are evaluated before the printer variables are bound: a
  ;; nested shape that prints and parses a number back must see the defaults.
  (destructuring-bind (x y) (rf-parts size 2)
    `(let ((xpx ,x) (xpy ,y))
       ,(rcase
          (1 `(length (let ((*print-circle* t))
                        (prin1-to-string (let ((xl (list xpx xpy))) (setf (cdr (last xl)) xl) xl)))))
          (1 `(length (let ((*print-circle* t)) (prin1-to-string (let ((xs (list xpx))) (list xs xs))))))
          (1 `(length (let ((*print-circle* nil)) (prin1-to-string (let ((xs (list xpx))) (list xs xs))))))
          (1 `(length (let ((*print-pretty* nil)) (prin1-to-string (list xpx (list xpy) "s")))))
          (1 `(length (let ((*print-length* 2)) (prin1-to-string (list xpx xpy 3 4)))))
          (1 `(length (let ((*print-level* 1)) (prin1-to-string (list xpx (list xpy (list 1)))))))
          (1 `(length (let ((*print-radix* t) (*print-base* 16)) (prin1-to-string xpx))))
          (1 `(length (let ((*print-escape* nil)) (prin1-to-string (list "a" #\b xpx)))))
          (1 `(length (write-to-string (list xpx xpy) :pretty nil :circle t)))
          (1 `(count #\Newline (let ((*print-pretty* t) (*print-right-margin* 10000))
                                 (prin1-to-string (list xpx xpy)))))))))

(defun rf-literal-form (size)
  ;; Literal arguments must be integers known at generation time.
  (let ((n (- (random 2000) 1000))
        (m (- (random 2000) 1000)))
    (destructuring-bind (x y) (rf-parts size 2)
      (rcase
        (1 `(+ (rf-s-a (rf-lit-struct ,n ,m)) (rf-s-b (rf-lit-struct ,m ,n)) ,x))
        (1 `(if (equalp (rf-lit-struct ,n 0) (make-rf-s :a ,n)) ,x ,y))
        (1 `(+ (rf-box-v (rf-lit-obj ,n ,m)) (rf-box-w (rf-lit-obj ,m ,n)) ,x))
        (1 `(+ (gethash "a" (rf-lit-ht ,n) 0) (gethash (list 1 2) (rf-lit-ht ,n) 0)
               (gethash 3 (rf-lit-ht ,n) 0) (hash-table-count (rf-lit-ht ,n)) ,x))
        (1 `(+ (nth 4 (rf-lit-circ ,n)) ,x))
        (1 `(floor (+ (aref (rf-lit-dvec ,n) 0) (aref (rf-lit-dvec ,n) 1) (float ,x 1d0))))
        (1 `(+ (reduce #'+ (rf-lit-ivec ,n)) ,x))
        (1 `(+ (aref (rf-lit-2d ,n) 0 0) (car (aref (rf-lit-2d ,n) 1 1)) ,x))
        (1 `(let ((xl (rf-lit-shared ,n))) (if (eq (first xl) (second xl)) ,x ,y)))
        (1 `(+ (char-code (char (rf-lit-str ,n) 1)) (length (rf-lit-str ,n)) ,x))
        (1 `(destructuring-bind (xa xb xc xd) (rf-lit-nums ,n)
              (+ (floor xa) (realpart xb) (floor xc) (floor xd) ,x)))
        (1 `(+ (length (symbol-name (rf-lit-sym))) (if (symbol-package (rf-lit-sym)) 1 0) ,x))
        (2 `(let ((xs (load-time-value (make-rf-s :a ,n))))
              (incf (rf-s-a xs)) (+ (rf-s-a xs) ,x)))
        (1 `(let ((xh (load-time-value (let ((xh (make-hash-table :test 'equal)))
                                         (setf (gethash "k" xh) ,n) xh))))
              (incf (gethash "k" xh)) (+ (gethash "k" xh) ,x)))
        (1 `(+ (rf-box-v (load-time-value (make-instance 'rf-box :v ,n) t)) ,x))
        (1 `(+ (load-time-value (rf-s-a (rf-lit-struct ,n ,m))) ,x))
        (1 `(let ((xv (load-time-value (vector ,n ,m) nil))) (incf (svref xv 0)) (+ (svref xv 0) ,x)))
        (1 `(eval-when (:compile-toplevel :load-toplevel :execute) (+ ,n ,x)))
        (1 `(+ (length (load-time-value (list (rf-lit-struct ,n ,m) (rf-lit-obj ,m ,n)))) ,x))))))

(defun make-random-integer-form (size)
  (if (and (>= size 4) (< (random 1.0) cl-user::*rf-extra-rate*))
      (rcase
        (3 (rf-float-form size))
        (2 (rf-string-form size))
        (2 (rf-array-form size))
        (2 (rf-mv-form size))
        (2 (rf-exit-form size))
        (2 (rf-call-form size))
        (2 (rf-place-form size))
        (2 (rf-condition-form size))
        (2 (rf-char-typed-form size))
        (2 (rf-clos-form size))
        (2 (rf-cond2-form size))
        (2 (rf-format-form size))
        (2 (rf-loop-form size))
        (2 (rf-string2-form size))
        (2 (rf-hash2-form size))
        (2 (rf-macro-form size))
        (2 (rf-seq-form size))
        (2 (rf-array2-form size))
        (2 (rf-closure-form size))
        (2 (rf-number-form size))
        (2 (rf-print-form size))
        (2 (rf-clos2-form size))
        (2 (rf-slots-form size))
        (2 (rf-restart2-form size))
        (2 (rf-array3-form size))
        (2 (rf-stream-form size))
        (2 (rf-printvar-form size))
        (4 (rf-literal-form size)))
      (funcall *rf-original-make-random-integer-form* size)))
